checkstyle/contribution

.gitignore
checkstyle-tester/README.md
checkstyle-tester/launch.sh
checkstyle-tester/projects-to-test-on.properties

- Replace git protocol from git to http
- Removed two directories that caused silent errors
- Added one quote old repo - Apache Ant

Fixes to run on clean repo

---

checkstyle-tester/README.md
checkstyle-tester/projects-to-test-on.properties

- added new small but very old repos to the list

- one more step for the guide

---

checkstyle-tester/README.md
checkstyle-tester/launch.sh
checkstyle-tester/projects-to-test-on.properties

- added ant repository that is quite old and good candidate when looking for violations

- Support to pull given commit so each execution of launch.sh validates the same sources

---

checkstyle-tester/projects-to-test-on.properties

Added CS-SI/Orikit to list of available projects to test on, information about projects site/commitId taken from travis

Added CS-SI/Orikit to projects to test on

---

qulice/pom.xml
qulice/qulice-checks.xml

- Checkstyle updated to 6.10-SNAPSHOT
- qulice-checks config were updated

Updates for qulice subproject

---

qulice/qulice-checks.xml
qulice/suppressions.xml

All suppressions were singled out into suppressions.xml

suppression filter was added

---

qulice/qulice-checks.xml

Report: http://baratali.github.io/qulice-checks/checkstyle.html

Custom Qulice Checks activated

---

checkstyle-tester/projects-to-test-on.properties

Update projects to test on

---

releasenotes-xdoc-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-xdoc-builder/src/main/java/com/github/checkstyle/CliProcessor.java

Pull #43: [release-notes-xdoc-builder] implement Builder patter for CliOptions class

---

checkstyle-tester/launch.sh

Should fix problem with sed on MacOS

checkstyle-tester launcher has been updated to detect OS and use appropriate sed flag

---

checkstyle-tester/launch_ahsm.sh

added error message if no parameters supplied.
added clean option.
added option to skip master install for cases where master's launch failed.
added "git pull" in-case local branch is not up to date with server branch.
added changes to original launcher.

updated launch_ahsm.sh

---

patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/StaxParserProcessor.java

it fixes the NPE for large inputs.

Fix for patch-diff-report-tool

---

patch-diff-report-tool/README.md
patch-diff-report-tool/config/import-control.xml
patch-diff-report-tool/pom.xml
patch-diff-report-tool/src/main/java/com/github/checkstyle/CliPathsHolder.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/PreliminaryVerifier.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java

Fixes for the first wave of code review: https://github.com/checkstyle/contribution/issues/50

Fixes for patch-diff-eport-tool.

---

patch-diff-report-tool/README.md
patch-diff-report-tool/config/import-control.xml
patch-diff-report-tool/pom.xml
patch-diff-report-tool/src/main/java/com/github/checkstyle/FilesystemUtils.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/PreparationUtils.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CheckstyleRecord.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CliPaths.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/ParsedContent.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/Statistics.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/StaxParserProcessor.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/AnchorCounter.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/JxrDummyLog.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
patch-diff-report-tool/src/main/resources/endPortion.template
patch-diff-report-tool/src/main/resources/headPortion.template
patch-diff-report-tool/src/main/resources/help.html
patch-diff-report-tool/src/main/resources/maven-theme.css
patch-diff-report-tool/src/main/resources/table.template

Fixes for the third part of the code review

Fixes for patch-diff-report-tool

---

patch-diff-report-tool/README.md
patch-diff-report-tool/src/main/java/com/github/checkstyle/CliArgsValidator.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java

Read over README and program help outputs to resolve issues I had understanding the program.

patch-diff-report-tool: updated documentation

---

checkstyle-tester/launch_diff.sh

Upgraded launch_ahsm to now use patch-diff-report-tool and renamed to launch_diff
**changes for that include:**
* new save ref directory, since the utility requires it
* had to remove `-set -e` for the diff util as it was canceling the entire script after one run
**Other changes include:**
* ignore cobertura on install
* verifying launch's pom against checkstyle's pom, to make sure the same version is being used. If there 2 aren't in-sync, you can run on an the wrong CS.
* print out of commands being run for debugging
* removed duplicated projects on main report using `containsElement`
* cleared final directory if it was already populated, so old reports and data dont remain
* captured number of differences and display them on the main report for guide to important projects to look at …

checkstyle-tester: updated launch_ahsm to launch_diff

---

checkstyle-web-tester/README.md
checkstyle-web-tester/checkstyle.php
checkstyle-web-tester/download-nightly.sh
checkstyle-web-tester/download-sevntu.sh

* added print option to look at token tree, creating reports from them aren't supported
* added sevntu download script for testing sevntu checks
* added url to read me as discussed in previous PR

Web tester update

---

checkstyle-tester/projects-to-test-on.properties

I changed FindBugs repo url from http://code.google.com to http://github.com in order to resolve the problem.

minor: code.google.com is findbugs was finally moved to github

---

checkstyle-tester/launch_diff.sh

* Added support for custom configs
* Added small support for repository specific configs
* Added support for "clean" and "-clean"
* Removed untracked git files from workspaces
* Added more skips during install

checkstyle-tester: updated launch_diff

---

checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-to-test-on.properties

Requested because of PR https://github.com/checkstyle/checkstyle/pull/3357#issuecomment-234233747
I synchronized all 3 property files, so they all contain the same information and easier to do merges/compares with.
I replaced all github protocols with git.
I updated Orekit with the latest commit.
I didn't see any other discrepancies between the properties and wrecker/travis configurations.

minor: synchronized and update projects properties

---

checkstyle-tester/projects-for-circle.properties

Issue #93, and requested in https://github.com/checkstyle/checkstyle/pull/3386#issuecomment-254698095
List of files came from a previous run in https://github.com/checkstyle/checkstyle/issues/3033#issuecomment-252448394
Am I to assume the properties for travis and projects to test on shouldn't be updated?

Issue #93: minimize exclude for jdk9 and use head

---

releasenotes-builder/README.md
releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
releasenotes-builder/src/main/java/com/github/checkstyle/publishers/README.md

Issue #73: Update an option and add examples of publication commands

---

releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java

Reverts checkstyle/contribution#129

Revert "minor: [releasenotes-builder] use Java 8 API instead of calls to 3rd-party libraries"

---

releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java

@romani 
Sorry, NPE was my fault .
I should have used:
```java
final Ref repoPeeled = repo.peel(referenceObj);
actualObjectId = Optional.ofNullable(repoPeeled.getPeeledObjectId())
.orElse(referenceObj.getObjectId());
```
instead of
```java
final Ref repoPeeled = repo.peel(referenceObj);
actualObjectId = Optional.of(repoPeeled.getPeeledObjectId())
.orElse(referenceObj.getObjectId());
```
to avoid NPE when repoPeeled.getPeeledObjectId() is equal to null . And looks like I tested only the second branch (when repoPeeled.getPeeledObjectId() was not equal to null). Now I tested both branches and fixed NPE.

Issue #130: [releasenotes-builder] use Java 8 API instead of calls to 3rd-party libraries (with NPE fix)

---

checkstyle-tester/my_check.xml

turned off `haltOnException` so regression never stops on exception. Will be reported as violation.

minor: added haltOnException

---

.gitignore
checkstyle-tester/diff.groovy

#51
@romani @rnveach 
1) Reports before fix will be generated into /reports/before_fix/{project_name} directory
2) Reports after fix will be generated into /reports/after_fix/{project_name} directory
3) Diff report will be generated into /reports/diff/{project_name} directory
4) Summary index.html will be in /reports/diff directory
Please, review
P.S.
I'll add documentation in README.md later when we agree on implementation and cli args.

Issue #51: Add diff report generation automation script in Groovy

---

checkstyle-tester/README.md
checkstyle-tester/README_OLD.md

doc: [checkstyle-tester] Update README.md to explain how to use new scripts written in Groovy

---

checkstyle-tester/launch.groovy
checkstyle-tester/projects-for-circle.properties
checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-to-test-on.properties

@romani 
Fixed ArrayOutOfBoundsException in launch.groovy in accordance with the [comment](https://github.com/checkstyle/contribution/issues/144#issuecomment-269139792).
Edited *.poperties files. Added empty pipe-delimited sections for the projects where commit id or excludes section are not specified.

[checkstyle-tester] Issue #144: Fix ArrayOutOfBoundsException in launch.groovy

---

checkstyle-tester/projects-to-test-on.properties

Issue #149: Fix line formatting in projects-to-test-on.properties

---

checkstyle-tester/launch_diff.sh
checkstyle-tester/pom.xml

Issue #152
added property and changed `launch_diff`.
Still need to change groovy which may take me some time since I never worked with it before.

Issue #152: turned tester failsOnError into property

---

checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-for-wercker.properties
checkstyle-tester/projects-to-test-on.properties

Issue #154
For the most part, added the project name to any excludes I thought were too broad.

Issue #154: made tester excludes more specific

---

checkstyle-tester/diff.groovy

Issue #158: Fix wrong throwing of IllegalStateException while checking changes in working directory

---

checkstyle-tester/launch.groovy

#160 
@rnveach 
Please, take a look at the changes.

Issue #160: Fix problem with diff report generation due to non-empty src directory

---

patch-diff-report-tool/README.md

Issue #153: Change patch-diff-report-tool REDME.md to point to groovy regression

---

.travis.yml

#166
@rnveach @romani 
Please, review and merge.

Issue #166: Create Travis test launches for groovy tester

---

checkstyle-tester/diff.groovy

Performed refactoring of diff.groovy in order to use automatic cli args validation from CliBuilder. (Similar to launch.groovy)

[checkstyle-tester] minor: diff.groovy refactoring

---

releasenotes-builder/src/main/resources/com/github/checkstyle/templates/gplus.template
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/twitter.template

Issue #127: Fix mistake in twitter.template and gplus.template for release-notes publication

---

.travis.yml
checkstyle-tester/README.md
checkstyle-tester/diff.groovy
checkstyle-tester/launch.groovy
patch-diff-report-tool/README.md

Issue #167: Add options to specify base config and patch config

---

releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_thymeleaf.template

Issue #117: Fix xdoc_thymeleaf.template to avoid Checkstyle violations

---

patch-diff-report-tool/README.md
patch-diff-report-tool/src/main/java/com/github/checkstyle/CliArgsValidator.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CliPaths.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java

`ResultPath` -> `OutputPath`.
`SourcePath` -> `RefFilesPath`

minor: fixed variable names to match options

---

patch-diff-report-tool/config/suppressions.xml
patch-diff-report-tool/pom.xml
patch-diff-report-tool/src/main/java/com/github/checkstyle/FilesystemUtils.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/AnchorCounter.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/CliArgsValidatorTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/FileSystemUtilsTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/internal/AbstractTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/parser/CheckstyleConfigurationsParserTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/parser/CheckstyleReportsParserTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/parser/ConfigurationMergerTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/parser/StaxUtilsTest.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/site/SiteGeneratorTest.java
patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
patch-diff-report-tool/src/test/resources/ExpectedReportEmpty.html
patch-diff-report-tool/src/test/resources/ExpectedReportEmptyWithConfig.html
patch-diff-report-tool/src/test/resources/InputBaseConfig.xml
patch-diff-report-tool/src/test/resources/InputBaseReportDifferences.xml
patch-diff-report-tool/src/test/resources/InputBaseReportEmpty.xml
patch-diff-report-tool/src/test/resources/InputPatchReportDifferences.xml
patch-diff-report-tool/src/test/resources/InputPatchReportEmpty.xml

Issue #176 
I will be splitting this issue up some.
The start of adding tests. Code coverage is not introduced yet.
I only removed dead code from the `main` folder that I was sure couldn't be executed.
`run` folder has empty files as they are required to exist but aren't required to be populated.
All XML files started out valid, but to appease some coverage I had to add invalid tags which don't interfere as the DTD is not attached to validate them.
Current line coverage is 93% total. Branch coverage is 79.5%.

Issue #176: started adding tests for patch-diff-report-tool

---

checkstyle-tester/diff.groovy

Issue #181: Skip tests execution during packaging of patch-diff-report-tool

---

patch-diff-report-tool/src/main/resources/header.template
patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
patch-diff-report-tool/src/test/resources/InputPatchReportSeverities.xml

Issue #187: added unique id to severity counts

---

checkstyle-tester/diff.groovy

Issue #141: Print SHA-1 of target commits (diff.groovy)

---

appveyor.yml
checkstyle-tester/diff.groovy
checkstyle-tester/launch.groovy

#177 
generateDiffReport and generateCheckstyleReport now receive too many parameters. Parameters should be represented as an objects of the specific class or the methods need to be refactored so as not to have so many parameters. Created an issue https://github.com/checkstyle/contribution/issues/182

Issue #17: Update windows CI to have run of groovy test tools

---

appveyor.yml
checkstyle-tester/README.md
checkstyle-tester/diff.groovy

#191 
'shortFilePaths' option for diff.groovy has been added.
@rnveach 
Please review and merge.

Issue #191: Add 'shortFilePaths' option for diff.groovy

---

checkstyle-tester/diff.groovy

Issue #199:  Add warning message to summary index page

---

releasenotes-builder/src/main/java/com/github/checkstyle/Constants.java
releasenotes-builder/src/main/java/com/github/checkstyle/TemplateProcessor.java

Issue #207: Add support for 'new module' label

---

.gitignore

minor: add .DS_Store to .gitignore

---

checkstyle-tester/README.md

Issue #211: Extend README.md of checkstyle-tester

---

checkstyle-tester/checks-sevntu-error.xml

Config that can be used with regression for sevntu.
See:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/571
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/572

config: added sevntu regression config

---

.travis.yml
checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
checkstyle-tester/diff.groovy

Issue #182
Part 1 of the refactoring. 
Next step will be decreasing the number of arguments in methods of diff.groovy (generateCheckstyleReport, generateDiffReport).

Issue #182: Extract config-related variables to separate class Config (part 1)

---

.travis.yml
checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
checkstyle-tester/diff.groovy

Issue #182: Extract config-related variables to separate class Config  (part 2)

---

checkstyle-tester/launch_diff.sh
checkstyle-tester/launch_diff_variables.sh

Moved customizable variables to another file. I use this between multiple scripts for my regression.
Renamed some variables to make more sense.
Added error messages for unknown options entered.
Added support for a custom master branch, and a patch only run.
Added warning to report that groovy has about excludes being ignored.

launch_diff: upgraded util to have same features as groovy scripts

---

patch-diff-report-tool/config/import-control.xml
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CheckstyleRecord.java
patch-diff-report-tool/src/main/resources/content.template
patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
patch-diff-report-tool/src/test/resources/ExpectedReportMessages.html
patch-diff-report-tool/src/test/resources/InputPatchReportMessages.xml

Issue #234: added retaining new line characters in report

---

patch-diff-report-tool/pom.xml
patch-diff-report-tool/src/test/java/com/github/checkstyle/CliArgsValidatorTest.java

Changing config to run checkstyle on sources directory.
I expect 1 violation.

config: changed patch-diff-report-tool to verify test sources style

---

releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java

Issue #212: Switch to Freemarker for releasenotes generation

---

checkstyle-tester/diff.groovy

Issue #249: Add commit hashes and messages to regression report

---

checkstyle-tester/checks-nonjavadoc-error.xml

fixed NPE for [https://github.com/checkstyle/checkstyle/pull/5026](https://github.com/checkstyle/checkstyle/pull/5026)

Issue #4557: fix NPE

---

checkstyle-tester/launch.groovy

Issue #263: converting system MAVEN_OPT variable to environment variable

---

.travis.yml
checkstyle-tester/launch.groovy

fixed [issue](https://github.com/checkstyle/contribution/issues/265)

Issue #265:fixed incorrect path for Windows

---

checkstyle-tester/projects-to-test-on.properties

Issue #4701
https://github.com/checkstyle/checkstyle/pull/5295#issuecomment-347017823

CS-SI/Orekit: use version 8.0.1

---

patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleConfigurationsParser.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
patch-diff-report-tool/src/test/resources/ExpectedReportConfigMessages.html
patch-diff-report-tool/src/test/resources/InputPatchConfigMessages.xml

Issue #260
I treat messages as properties for the config as they are almost the same.

Issue #260: added config message property to the report display

---

checkstyle-tester/LAUNCH_GROOVY_README.md
checkstyle-tester/diff.groovy
checkstyle-tester/launch.groovy

Issue #276: Allow providing Checkstyle version in launch.groovy

---

jsoref-spellchecker/whitelist.words

For checkstyle/checkstyle#5703
Based on https://travis-ci.org/checkstyle/checkstyle/jobs/363841975

spelling: update to collapse word families

---

jsoref-spellchecker/exclude.pl

for checkstyle/checkstyle#5719

minor: migrate exclusion code from checkstyle

---

jsoref-spellchecker/exclude.pl

This is a fix based on an item in checkstyle/checkstyle#5693

minor: fix exclude regex

---

.travis.yml
checkstyle-tester/LAUNCH_GROOVY_README.md
checkstyle-tester/launch.groovy

Issue #302: added sevntu version option to launch groovy

---

checkstyle-tester/checks-sevntu-error.xml

Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/691

sevntu: added missing modules to checks-sevntu-error.xml

---

checkstyle-tester/checks-sevntu-error.xml

Copied over checkstyle's changes including property name change, property value change, and 100 character line restriction.
Confirmed config will pass.

sevntu: resynchronized checks-sevntu-error.xml with checkstyle's config

---

releasenotes-builder/README.md
releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
releasenotes-builder/src/main/java/com/github/checkstyle/Main.java

Issue #309
Not to be merged yet.

Issue #309: allowed other repositories to use releasenotes builder

---

releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_all_sections.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_breaking_compatibility_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_bug_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_new_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_notes_section.txt

Issue #311: escaped html in the release notes

---

releasenotes-builder/README.md
releasenotes-builder/config/import-control.xml
releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
releasenotes-builder/src/main/java/com/github/checkstyle/TemplateProcessor.java
releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java

Issue #309
We are allowing external files so each repository can define its own template and not have to wait on this project to update it if a change is needed.
Sevntu's xdoc template will be:
````
<#escape x as x?html>
<div id="${releaseNo}" class="spoiler pre_opened_spoiler">
<div class="name"><span><h3>Release ${releaseNo}</h3></span></div>
<div class="text">
<#if breakingMessages?has_content>
<p>Breaking backward compatibility:</p>
<ul>
<#list breakingMessages as message>
<li>
${message.title}.
Author: ${message.author}<#if message.issueNo != -1>
<a href="https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/${message.issueNo}">#${message.issueNo}</a></#if>
</li>
</#list>
</ul>
</#if>
<#if newMessages?has_content>
<p>New:</p>
<ul>
<#list newMessages as message>
<li> …
```

Issue #309: allow external template files

---

appveyor.yml

Issue #316: remove cygwin from appveyor

---

releasenotes-builder/src/main/java/com/github/checkstyle/Main.java

Fix for https://travis-ci.org/checkstyle/checkstyle/jobs/398967176#L741

minor: fixed wrong template resource locations

---

releasenotes-builder/src/main/java/com/github/checkstyle/ReleaseNotesMessage.java
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_all_sections.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_breaking_compatibility_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_bug_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_new_section.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/correct_notes_section.txt

Issue #312: split lines to make template shorter

---

releasenotes-builder/config/import-control-test.xml
releasenotes-builder/config/import-control.xml
releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/package-info.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/Constants.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/Result.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/package-info.java
releasenotes-builder/src/main/java/com/github/checkstyle/templates/TemplateProcessor.java
releasenotes-builder/src/main/java/com/github/checkstyle/templates/package-info.java
releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java

Made the separation between packages clearer.
Moved some code from Main to their specific package.
Redid the import control file.
Eventually I want to have actual regression tests.

minor: restructured packages to show clearer separation

---

checkstyle-tester/checks-nonjavadoc-error.xml

https://github.com/checkstyle/checkstyle/issues/5899

config: add new InterfaceMemberImpliedModifier Check

---

checkstyle-tester/checks-import-order/checks-imports-error-guava.xml
checkstyle-tester/checks-import-order/checks-imports-error-java-design-patterns.xml
checkstyle-tester/checks-import-order/projects-to-test-imports-guava.properties
checkstyle-tester/checks-import-order/projects-to-test-imports-java-design-patterns.properties

Issue #329 
Import order configuration for guava and java-design-patterns

Issue #329: config to validate imports

---

releasenotes-builder/config/intellij-idea-inspections.xml
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/Result.java
releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java

I335 inspections

---

checkstyle-tester/checks-nonjavadoc-error.xml
examples/checks/all-checkstyle-checks.xml
examples/linkErrors2Source/checkstyle-noframes.xsl
patch-diff-report-tool/config/import-control-test.xml
releasenotes-builder/config/import-control-test.xml
releasenotes-builder/config/suppressions.xml
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/gplus.template
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/mailing_list.template
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/rss.template
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/twitter.template
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistAll.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBreakingCompatibility.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBug.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistMisc.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistNew.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterGplusAll.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterGplusBreakingCompatibility.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterGplusBug.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterGplusMisc.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterGplusNew.txt
xsl/checkstyle-author.xsl
xsl/checkstyle-frames-errors.xsl
xsl/checkstyle-frames.xsl
xsl/checkstyle-noframes-severity-sorted.xsl
xsl/checkstyle-noframes-sorted.xsl
xsl/checkstyle-noframes.xsl

Issue #338: switch to https://checkstyle.org

---

releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

https://teamcity.jetbrains.com/viewLog.html?buildId=1861633&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsMaster

minor: remove redundant suppressions

---

checkstyle-tester/launch_diff.sh
checkstyle-tester/launch_diff_antlr.sh
checkstyle-tester/launch_diff_variables.sh
checkstyle-tester/launch_pitest.sh
checkstyle-tester/sevntu_launch_diff.sh

Added pitest script that will generate a specific report or all reports. All reports includes index report with number of surviving counts for each sub-report.
Enforced `CONTACTSERVER` on all repositories except for checkstyle pull remote.
Updated `launch_diff_antlr.sh` to latest logic.
Other miscellaneous updates.

updated all launch scripts

---

checkstyle-web-tester/checkstyle.php

Added security for DTD system URL.
Added the ability to print suppressions.
Added minor displays to denote the file names to the text areas.
Broke the output on words if a word was too long.

checkstyle-web-tester: added new security and features

---

checkstyle-tester/pom.xml

This is a fix for https://github.com/checkstyle/checkstyle/pull/6553#issuecomment-471487361 .

config: updated maven plugin version for checkstyle-tester

---

checkstyle-tester/projects-for-circle.properties

PR for https://github.com/checkstyle/checkstyle/pull/6551 to ignore non-compilable files.

config: added non-compilable files for tapestry-5 to ignore list

---

checkstyle-tester/README.md

Improved documentation based on questions at https://github.com/checkstyle/checkstyle/pull/6530
Added documentation on how to use regression to kill pitest mutations.
Clarified that regression can't really be used for sevntu.
Removed old project that was merged into contribution.

doc: improved checkstyle-tester documentation

---

checkstyle-tester/launch.groovy
checkstyle-tester/projects-for-circle.properties
checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-for-wercker.properties
checkstyle-tester/projects-to-test-on.properties

Issue #355: support local projects VCS-independently

---

checkstyle-tester/README.md

Issue #355: add some documentation for local type

---

checkstyle-tester/checks-nonjavadoc-error.xml

Related to issue https://github.com/checkstyle/checkstyle/issues/6462 and PR https://github.com/checkstyle/checkstyle/pull/6530

config: remove AnnotationLocation token PARAMETER_DEF as it will be removed from Checkstyle for #6462

---

releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBreakingCompatibility.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBug.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistMisc.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistNew.txt

Issue #312
This should close the issue.

Issue #312: only applied short width title to xdoc

---

checkstyle-tester/checks-nonjavadoc-error.xml

For PR https://github.com/checkstyle/checkstyle/pull/6554 and Issue https://github.com/checkstyle/checkstyle/issues/5411 .
Can only be merged when the other PR is merged otherwise it will break the other CI.
This CI will not pass until the other PR is merged first.
Chicken and Egg.

config: added MissingJavadocTypeCheck

---

checkstyle-tester/checks-nonjavadoc-error.xml

For PR https://github.com/checkstyle/checkstyle/pull/6639 and Issue checkstyle/checkstyle#5411 .
Can only be merged when the other PR is merged otherwise it will break the other CI.

config: added MissingJavadocMethodCheck

---

checkstyle-tester/checks-nonjavadoc-error.xml

Add check from https://github.com/checkstyle/checkstyle/pull/6782

config: added UnnecessarySemicolonInEnumerationCheck

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/6799

Add UnnecessarySemicolonInTryWithResources

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/6798

Add MissingJavadocPackage

---

checkstyle-tester/checks-sevntu-error.xml

This PR addresses issue #380 and changes the file `checkstyle-tester/checks-sevntu-error.xml` which is necessary in order to merge sevntu-checkstyle PR [#742](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/742).

Issue #380 New check: Jsr305Annotations

---

checkstyle-tester/checks-nonjavadoc-error.xml

I would like to make an PR here to get the checkstyle OrderedPropertiesCheck merged.

Issue #6311: Based on OrderedPropertiesCheck of checkstyle

---

checkstyle-tester/checks-nonjavadoc-error.xml

This is in support of https://github.com/checkstyle/checkstyle/pull/6718

config: add InvalidJavadocPositionCheck

---

patch-diff-report-tool/pom.xml

This was reported by synk but it didn't show a way to fix it so I am checking if upgrading the version does.

config: upgrade jgit to 5.4.0.201906121030-r

---

checkstyle-tester/checks-nonjavadoc-error.xml
checkstyle-tester/checks-only-javadoc-error.xml

This change is for PR https://github.com/checkstyle/checkstyle/pull/6862

config: move MissingDeprecated to javadoc only config

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/6888

config: add UnnecessarySemicolonAfterTypeMemberDeclaration

---

checkstyle-tester/pom.xml

Identified at https://github.com/checkstyle/checkstyle/pull/7088

config: upgrade maven-checkstyle-plugin to 3.1.0

---

checkstyle-tester/checks-only-javadoc-error.xml

Add JavadocContentLocation check to checks-only-javadoc-error.xml
reference: checkstyle/checkstyle#6724

config: added JavadocContentLocationCheck

---

checkstyle-tester/projects-to-test-on.properties

https://github.com/checkstyle/checkstyle/pull/7315#issuecomment-562213799

config: add spring-integration

---

releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

checkstyle/checkstyle#7224: dependabot config

---

releasenotes-builder/config/intellij-idea-inspections.xml

https://teamcity.jetbrains.com/viewLog.html?buildId=2667810&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsMaster
based on https://github.com/checkstyle/checkstyle/commit/3de6a350321e6f2cfb5da3a7bbf8b9912d57f0a5

minor: fix teamcity violations

---

patch-diff-report-tool/src/main/resources/content.template
patch-diff-report-tool/src/main/resources/maven-base.css
patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
patch-diff-report-tool/src/test/resources/ExpectedReportMessages.html
patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
patch-diff-report-tool/src/test/resources/ExpectedReportTextMode.html

Issue #422
result is show in issue.

Issue #422: diff repot: wrap words, highlight target

---

checkstyle-tester/checks-nonjavadoc-error.xml

for https://github.com/checkstyle/checkstyle/pull/7228

Issue checkstyle/checkstyle#6971: add NoEnumTrailingComma to checks-nonjavadoc-error.xml

---

patch-diff-report-tool/src/main/resources/maven-theme.css

result:
https://romani.github.io/h3-small/diff/guava/index.html
from mobile:
from laptop:

minor: patch-diff-report-tool: change font of h3 to small as file path is minor information

---

.travis.yml

Issue checkstyle/checkstyle#7444: remove Google maven central mirror

---

checkstyle-tester/checks-nonjavadoc-error.xml

Identified at https://github.com/checkstyle/checkstyle/pull/7455

config: add NoEnumTrailingComma to regression configs

---

checkstyle-tester/checks-nonjavadoc-error.xml

For https://github.com/checkstyle/checkstyle/pull/7387

config: add AvoidNoArgumentSuperConstructorCall

---

checkstyle-tester/checks-import-order/projects-to-test-imports-guava.properties
checkstyle-tester/projects-for-circle.properties
checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-for-wercker.properties
checkstyle-tester/projects-to-test-on.properties

need to be merged after checkstyle/checkstyle#7407

checkstyle/checkstyle#7407: enable latest guava

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/7457

config: add AvoidDoubleBraceInitializationCheck

---

.ci/travis.sh
.gitignore
checkstyle-tester/launch.groovy

Config ci temp folder

---

.ci/travis.sh
checkstyle-tester/projects-for-travis.properties

Issue #450
I copy property file to temp folder to avoid changes in repository (to void git changes)

Issue #450: ci should run checkstyle-tester/diff.groovy on project that does have incompilable sources

---

checkstyle-tester/README.md

Identified at https://github.com/checkstyle/checkstyle/pull/7774#issuecomment-596045890

doc: add clone instructions to setup

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/7935

doc: add UnnecessarySemicolonAfterOuterTypeMemberDeclaration

---

checkstyle-tester/diff.groovy

Issue #462: updated diff site generation to publish property files, [example here.](https://nmancus1.github.io/Contribution-Issue-792/diff/index.html)

Issue #462: diff.groovy: add property file used for testing to report

---

releasenotes-builder/pom.xml

https://app.snyk.io/org/checkstyle/project/6464a1a8-78eb-4b93-aa92-c6889786636a?utm_campaign=weekly_report&utm_source=Project&fromGitHubAuth=true

config: bump github-api to 1.99 to resolve security issue reported by snyk

---

checkstyle-tester/README.md

From https://github.com/checkstyle/checkstyle/pull/8093#issuecomment-617277511
Sometimes we need to debug the regression generator.

doc: add lauch.groovy troubleshooting hint

---

checkstyle-tester/projects-to-test-on.properties

Issue #473: add jdk11 and jdk14 to checkstyle-tester projects

---

checkstyle-tester/diff.groovy

add error print to diff.groovy

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/8161

config: add NoCodeInFile

---

checkstyle-tester/diff.groovy

Fixes Issue #461 
Diff Report: [here](https://abhishek-kumar09.github.io/IndentaionReport/reports2/diff/index.html) 
Screenshot until site is resolved:

Issue #461: Add information about added/removed violations on main report page

---

checkstyle-tester/README.md

minor: remove extra spaces from README.md

minor: remove extra spaces from README.md

---

checkstyle-tester/README.md

minor: Update checkstyle-tester README.md to provide guide for Check and AST regression testing.

minor: Update checkstyle-tester README.md 

---

checkstyle-tester/diff.groovy

Issue #430: add base and patch configs to diff report
Examples:
Basic Difference Report
Link: https://nmancus1.github.io/diff_single_config/
Difference Report with Different Base and Patch Config
Link: https://nmancus1.github.io/diff_base_patch_example/

Issue #430: add base and patch configs to diff report

---

checkstyle-tester/pom.xml

https://github.com/checkstyle/patch-filters/issues/34

minor: use system variable to customize path to a patch file

---

checkstyle-tester/checks-nonjavadoc-error.xml

Related to [checkstyle #8417](https://github.com/checkstyle/checkstyle/pull/8417).

config: add PatternVariableName check

---

checkstyle-tester/checks-nonjavadoc-error.xml

Related to https://github.com/checkstyle/checkstyle/pull/8586

config: add RecordTypeParameterNameCheck

---

checkstyle-tester/checks-nonjavadoc-error.xml

Related to https://github.com/checkstyle/checkstyle/pull/8595

config: add RecordComponentNumberCheck

---

checkstyle-tester/checks-nonjavadoc-error.xml

Related to https://github.com/checkstyle/checkstyle/pull/8766.

config: add IllegalIdentifierName to checks-nonjavadoc-error.xml

---

checkstyle-tester/diff.groovy

Issue #493: Removed regex violations in main Diff report page

---

checkstyle-tester/projects-for-travis.properties
checkstyle-tester/projects-for-wercker.properties
checkstyle-tester/projects-to-test-on.properties

…folders as there are bunch of new jdk files
discussed at https://github.com/checkstyle/checkstyle/pull/8892#issuecomment-707152059

config: update checkstyle's ignore list to execute on non-compilable 

---

checkstyle-tester/launch.groovy

This PR will add the ability to allow extra arguments to be passed to Maven for Checkstyle execution, related to https://github.com/checkstyle/checkstyle/issues/8901.
Proof of successful usage: https://checkstyle.semaphoreci.com/jobs/f0589693-fcba-4781-b12e-e32d2ae2f225

infra: add CLI option to supply additional Maven args

---

checkstyle-tester/projects-to-test-on.properties

and confuse contributors on is it possible to use it

minor: remove openjdk14 as it is not complete 

---

checkstyle-tester/checks-nonjavadoc-error.xml

add check for https://github.com/checkstyle/checkstyle/pull/8896

config: add LambdaBodyLength

---

.ci/travis.sh
.mdl_style.rb
.mdlrc
.travis.yml
README.md
checkstyle-tester/LAUNCH_GROOVY_README.md
checkstyle-tester/README.md
checkstyle-tester/README_MANUAL_EXECUTION.md
checkstyle-tester/README_OLD.md
checkstyle-web-tester/README.md
devops/ansible/Readme.md
patch-diff-report-tool/README.md
releasenotes-builder/README.md
releasenotes-builder/src/main/java/com/github/checkstyle/publishers/README.md

Issue #513
Fixes:
* top level header [md002](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md002---first-header-should-be-a-top-level-header), [md041](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header)
* trailing space [md009](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md009---trailing-spaces)
* code-blocks [md031](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines), [md040](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md040---fenced-code-blocks-should-have-a-language-specified)
* inlline HTML [md033](https://github.com/markdownlint/markdownlint/blob/mast …

Issue #513: add markdown lint to ci

---

checkstyle-tester/README.md

based my experience on report config preparation

doc: add links to quickly open templates for copy to personal gist

---

checkstyle-tester/checks-only-javadoc-error.xml

add check for checkstyle/checkstyle#9006

config: add JavadocMissingLeadingAsterisk

---

checkstyle-tester/checks-nonjavadoc-error.xml

add check for https://github.com/checkstyle/checkstyle/pull/8902

config: add MatchXpathCheck

---

checkstyle-tester/diff.groovy

Issue #539: diff.groovy should allow configs in other directories
Since this was only an issue when generating the html files to be crosslinked for the final report (not while generating the individual checkstyle reports), I simply copied all config files to be used to the working directory where the summary html is made. Instead of differentiating between different types of config files, this ends up just overwriting `projects-to-test-on.properties` with itself; I thought this would have no adverse affects and would make the code easier to read and maintain in the future.
Proof that this change fixes the final report regeneration mentioned in #539 : https://travis-ci.org/github/checkstyle/regression-tool/jobs/755600670

Issue #539: diff.groovy should allow configs in other directories

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for https://github.com/checkstyle/checkstyle/pull/9180

config: add RecordComponentNameCheck

---

releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

Combined PR with [#9364](https://github.com/checkstyle/checkstyle/pull/9364) for  [Issue  #8928](https://github.com/checkstyle/checkstyle/issues/8928)

minor: Add supplemental prefix in release-notes builder

---

checkstyle-tester/checks-sevntu-error.xml

From https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/834
checkstyle PR in https://github.com/checkstyle/checkstyle/pull/9785
Sevntu PR: https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/834

config: add preferMethodReference

---

comment-action/README.md

add small description why we need this action

doc: add readme for comment action module

---

releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/Result.java

Issue #566 
Missing Javadoc comments for releasenotes-builder.

Issue #566: add missing javadoc for releasenotes-builder

---

checkstyle-tester/launch_diff.sh
checkstyle-tester/launch_diff_antlr.sh
checkstyle-tester/launch_pitest.sh
checkstyle-tester/sevntu_launch_diff.sh

launch_diff :
* supports multiple configurations
all:
* executes ignored modules
* updated reports to be more similar to groovy's version

update all launch scripts

---

.travis.yml

from https://github.com/checkstyle/contribution/pull/569#issuecomment-955700289

minor: print groovy version

---

.travis.yml
appveyor.yml

in context https://github.com/checkstyle/checkstyle/issues/10778
not all problems are resolved, but some jobs are moved to new arch.

infra: change travis arch to not use 'paid' credits

---

.travis.yml

#573
first commit is another PR - not or review.
last commit is actual fix and advise from Travis support, it was passed before commits re-organization
https://app.travis-ci.com/github/checkstyle/contribution/builds/241105673

573 groovy

---

.travis.yml
README.md
checkstyle-tester/README.md
checkstyle-tester/README_GET_RAW_LINK.md

Issue #534: enable markdown lint

---

.ci/travis.sh
.travis.yml

config: activate codenarc #448

---

checkstyle-tester/projects-for-wercker.properties

Issue #564: Exclude InputXpathMapperStringConcat from wercker.properties

---

appveyor.yml

Issue #576: use direct link to groovy download

---

checkstyle-tester/projects-to-test-on-for-github-action.properties

Related to comments at https://github.com/checkstyle/checkstyle/pull/10956#issuecomment-970332760

minor: remove excludes(related to checkstyle#10956)

---

checkstyle-tester/checks-nonjavadoc-error.xml

Since (https://github.com/checkstyle/checkstyle/issues/9984) has not been resolved, we have been failing to add checks to configs here used for CI in main checkstyle repo.

minor: add new check NoWhitespaceBeforeCaseDefaultColon

---

checkstyle-tester/diff.groovy

Issue #580: Remove excludes warning from diff.groovy report

---

patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CheckstyleRecord.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/data/Statistics.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/TextTransform.java

major: (https://github.com/checkstyle/checkstyle/pull/11053)

minor: remove redundant this (Issue checkstyle#7895)

---

checkstyle-tester/checks-nonjavadoc-error.xml

Issue https://github.com/checkstyle/checkstyle/issues/7504 and PR https://github.com/checkstyle/checkstyle/pull/10930

minor: add new check UnusedLocalVariable

---

appveyor.yml

detected at https://github.com/checkstyle/contribution/pull/598?notification_referrer_id=NT_kwDOAAxnuLEzMzQwNjAzNTU2OjgxMjk4NA#issuecomment-1080011168

config: migrate to jdk11 in appveyor

---

.travis.yml

detected at https://github.com/checkstyle/contribution/pull/598?notification_referrer_id=NT_kwDOAAxnuLEzMzQwNjAzNTU2OjgxMjk4NA#issuecomment-1080011168

config: migrate travil to jdk11

---

checkstyle-tester/projects-to-test-on.properties

Also fixes failure noted at https://github.com/checkstyle/checkstyle/issues/11685

Issue #250: update versions of some projects

---

checkstyle-tester/checks-nonjavadoc-error.xml
checkstyle-tester/checks-only-javadoc-error.xml
checkstyle-tester/checks-sevntu-error.xml

Copied values from https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml

minor: updates configuration dtd

---

checkstyle-tester/latest-projects-to-test-on.properties

This is just a copy/paste/modify of the existing projects file, where specific commits and tags have been removed to allow us to test on the latest version of the project.
See https://github.com/checkstyle/checkstyle/pull/11805#issue-1291342040 and https://github.com/checkstyle/checkstyle/pull/11805#issuecomment-1172370264  for proof that Checkstyle can complete execution with these projects/ properties.

minor: create latest projects file for regression testing

---

releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

Issue #574: releasenotes-builder: fail execution if multiple labels

---

releasenotes-builder/README.md
releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/package-info.java

https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_ContributionIdeaInspectionsPullRequest/3907566?buildTab=Inspection

minor: fix TC violation for spelling

---

releasenotes-builder/config/intellij-idea-inspections.xml
releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/Constants.java

From https://github.com/checkstyle/checkstyle/pull/11691
Failing CI at https://checkstyle.semaphoreci.com/jobs/f69a7a67-39d9-4fa3-b0a3-9ebd39b61c51
-----------------------
Description of "PublicStaticArrayField":
>Such fields are often used to store arrays of constant values. Still, they represent a security hazard, as their contents may be modified, even if the field is declared final.

Pull checkstyle#631: fix checkstyle violations from main repo

---

.ci/bump-cs-version-in-releasenotes-builder.sh

Issue #634: satelite projects should use latest checkstyle as soon at is appears in maven repo

---

releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

Issue #614: Suppress UseOfSystemOutOrSystemErr IDEA violations

---

releasenotes-builder/config/checkstyle.properties

#614 
Suppression was generated by IDEA

Issue #614: Suppress UnusedProperty IDEA violations

---

.github/workflows/bump_project_version.yml

Issue #649: Disable execution in bump project version action

---

releasenotes-builder/src/main/java/com/github/checkstyle/Main.java

from https://github.com/checkstyle/checkstyle/issues/12169#issuecomment-1239316050

minor: fix exception print in releasenotes-builder

---

checkstyle-tester/checks-nonjavadoc-error.xml

PR for [Checkstyle #9728](https://github.com/checkstyle/checkstyle/pull/9728)

config: add NoWhitespaceBeforeCaseDefaultColon

---

releasenotes-builder/config/intellij-idea-inspection-scope.xml

Issue #626: ignore read me for teamcity

---

releasenotes-builder/pom.xml
releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java

infra: upgrade dependency versions for releasenotes-builder

---

releasenotes-builder/src/main/java/com/github/checkstyle/templates/TemplateProcessor.java

Issue #626 and this will close the issue

Issue #626: suppressed try with resource in TemplateProcessor

---

checkstyle-tester/diff.groovy

Issue #663
New indentation is to prevent IAE being thrown for no arguments.
New Output:
````
PS M:\checkstyleWorkspaceEclipse\contribution\checkstyle-tester> groovy .\diff.groovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/RickysPrograms/groovy-2.5.18/lib/groovy-2.5.18.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
error: Missing required options: r, p, l
usage: groovy diff.groovy [options]
options: …
```

Issue #663: resolves NPE for diff.groovy

---

.ci/travis.sh
checkstyle-tester/diff.groovy

Issue #448

---

devops/docker/idea-image/Dockerfile

Related to checkstyle/checkstyle#12087

infra: add dockerfile for idea

---

patch-diff-report-tool/config/ant-phase-verify.xml
patch-diff-report-tool/config/checkstyle.properties
patch-diff-report-tool/pom.xml
releasenotes-builder/config/ant-phase-verify.xml
releasenotes-builder/config/checkstyle.properties
releasenotes-builder/pom.xml

Issue #672
I was not finding any instances of skipping checkstyle execution in this repo or in main repo for the modified projects.

Issue #672: convert maven-checkstyle-plugin to ant

---

checkstyle-tester/README.md

minor: Update the readme file

---

devops/docker/README.md

Fixes from https://github.com/checkstyle/contribution/pull/684#issuecomment-1298581116

doc: corrections to docker readme

---

.ci/travis.sh
checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
checkstyle-tester/diff.groovy

Issue #448: resolve more codenarcs

---

releasenotes-builder/README.md
releasenotes-builder/config/suppressions.xml
releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java

Missing options and mis-spellings. Also corrected periods.

minor: correct release notes options

---

.gitignore

Resolves https://github.com/checkstyle/contribution/pull/706#issuecomment-1328058381
> we can add it to https://github.com/checkstyle/contribution/blob/master/.gitignore to not bother us next time

config: ignore .attach_pid files

---

.ci/travis.sh
checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt

Issue #448: resolve final codenarc violation

---

checkstyle-tester/diff.groovy

Issue #725: adds no transfer progress to diff.groovy

---

releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractPathTestSupport.java
releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractReleaseNotesTestSupport.java
releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt

Issue #327: releasenotes-builder: add better in-depth tests

---

releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractReleaseNotesTestSupport.java
releasenotes-builder/src/test/java/com/github/checkstyle/internal/RevCommitUtil.java

Issue #614
This doesn't resolve all of them but it is a start.

Issue #614: resolves idea violations

---

releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
releasenotes-builder/src/test/resources/com/github/checkstyle/githubIssueNotFound.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/twitterIssueNotFound.txt
releasenotes-builder/src/test/resources/com/github/checkstyle/xdocIssueNotFound.txt

https://github.com/checkstyle/contribution/issues/711

 Issue #711: adds warning when issue cannot be found 

---

bcel/docs/BCELConfig.xml
checkstyle-tester/checks-import-order/checks-imports-error-guava.xml
checkstyle-tester/checks-import-order/checks-imports-error-java-design-patterns.xml
checkstyle-tester/diff-groovy-regression-config.xml
checkstyle-web-tester/checkstyle.php
examples/XInclude/index.html
examples/XInclude/treewalker.xml
examples/checks/com/puppycrawl/tools/checkstyle/checks/xpath/xpath_config.xml
examples/checks/mycompany_conf.xml
examples/conf/BlochEffectiveJava.xml
examples/conf/openorb.xml
examples/conf/template_config.xml
patch-diff-report-tool/config/import-control.xml
patch-diff-report-tool/config/suppressions.xml
releasenotes-builder/config/suppressions.xml

Issue #741
```
~/java/github/checkstyle/contribution [i741-domain L|] 
$ ag "Puppy Crawl"
✘-1 
```

Issue #741: move all reference of dtd to checkstyle.org

---

.circleci/config.yml

Activating CircleCI in this repo, we are long overdue for this. We will probably need to merge this before CircleCI will run at all. I can follow up with PR to make sure all is working and that we disable travis.

infra: migrate travis jobs to CircleCI

---

patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleConfigurationsParser.java

Issue #268: ensure file name is added to configuration exception

---

patch-diff-report-tool/src/main/resources/header.template
patch-diff-report-tool/src/test/resources/ExpectedReportConfigMessages.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
patch-diff-report-tool/src/test/resources/ExpectedReportEmpty.html
patch-diff-report-tool/src/test/resources/ExpectedReportEmptyWithConfig.html
patch-diff-report-tool/src/test/resources/ExpectedReportMessages.html
patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
patch-diff-report-tool/src/test/resources/ExpectedReportTextMode.html

Issue #453: add links to report headings in patch-diff-report

---

checkstyle-tester/checks-nonjavadoc-error.xml

Issue #661: expands regression for VariableDeclarationUsageDistance

---

README.md

Removes travis badge since travis is disabled now.

minor: remove travis badge

---

checkstyle-tester/projects-to-test-on.properties

````
Running Launch on spoon ...
Reseting git sources to commit 'spoon-core-10.1.1'
fatal: ambiguous argument 'spoon-core-10.1.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
````
````
www-data@ubuntu:~/regression_repositories/spoon$ git fetch origin
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 28 (delta 12), reused 13 (delta 11), pack-reused 8
Unpacking objects: 100% (28/28), done.
From https://github.com/INRIA/spoon
388138e1..0946b9fa  master                        -> origin/master
* [new branch]        MartinWitt-patch-1            -> origin/MartinWitt-patch-1
* [new branch] …
```

minor: moves spoon to a valid branch name

---

checkstyle-tester/diff.groovy

Issue #766: ensures color spans are closed

---

releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractReleaseNotesTestSupport.java

Resolves https://github.com/checkstyle/checkstyle/issues/13047

Pull #781: Print links of offending issues

---

comment-action/action.yml

Related: https://github.com/checkstyle/checkstyle/issues/13045

Issue #13045: update node version

---

checkstyle-tester/README_MANUAL_EXECUTION.md

Issue #812: Correct Linting error

---

checkstyle-tester/github-action-projects1.properties

detected at checkstyle/checkstyle#14022

infra: exclude non-compiled file from execution

---

checkstyle-tester/README.md
checkstyle-tester/diff.groovy

Fixes #818
Fixes #351
tested on local:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.911 s
[INFO] Finished at: 2023-12-02T17:22:12-08:00
[INFO] ------------------------------------------------------------------------
Starting diff report generation ...
Running command: java -jar /home/rivanov/java/github/checkstyle/contribution/patch-diff-report-tool/target/patch-diff-report-tool-0.1-SNAPSHOT-jar-with-dependencies.jar --patchReport reports/plan3d/Issue_3132/guava/checkstyle-result.xml
--output reports/diff/guava --patchConfig my-config.xml --baseReport reports/master/guava/checkstyle-result.xml --baseConfig my-config.xml …
```

I818 shallow clone

---

checkstyle-tester/checks-nonjavadoc-error.xml

For https://github.com/checkstyle/checkstyle/pull/14791.
As discussed in https://github.com/checkstyle/checkstyle/pull/14791#issuecomment-2067709722
Added property for MagicNumberCheck to detect regression.

minor: change config of MagicNumberCheck

---

appveyor.yml

Detected at https://github.com/checkstyle/contribution/pull/843#issuecomment-2102683745

infra: Update appveyor.yml

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of https://github.com/checkstyle/checkstyle/pull/14749
add new module ConstructorsDeclarationGrouping

config: new check ConstructorsDeclarationGrouping

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of checkstyle/checkstyle#15113

Config: New Check MissingNullCaseInSwitch

---

checkstyle-tester/checks-nonjavadoc-error.xml

https://github.com/checkstyle/checkstyle/pull/15199

config: WhenShouldBeUsed

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of https://github.com/checkstyle/checkstyle/pull/15337

Config: New Check SealedShouldHavePermitsList

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of #https://github.com/checkstyle/checkstyle/pull/15358

Config: New Check UnusedCatchParameterShouldBeUnnamed

---

patch-diff-report-tool/config/ant-phase-verify.xml
patch-diff-report-tool/pom.xml
releasenotes-builder/config/ant-phase-verify.xml
releasenotes-builder/pom.xml

part of https://github.com/checkstyle/checkstyle/pull/15376

minor: define the new property in pom.xml and transfer it to ant run

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of https://github.com/checkstyle/checkstyle/pull/15480

Config: New Check UnusedLambdaParameterShouldBeUnnamed

---

patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleConfigurationsParser.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/TextTransform.java
patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
patch-diff-report-tool/src/test/java/com/github/checkstyle/CliArgsValidatorTest.java

Issue #933: Rename CatchParameterName in patch-diff-report-tool

---

checkstyle-tester/checks-nonjavadoc-error.xml

part of #https://github.com/checkstyle/checkstyle/pull/16489

Config: New Check UnnecessaryNullCheckWithInstanceOf

---

.circleci/config.yml
devops/docker/no-exception-build-image/jdk-17-groovy-git-mvn/Dockerfile

Part of : https://github.com/checkstyle/checkstyle/issues/17168

infra: Added Docker File for Java 17 Build

---

checkstyle-tester/checks-nonjavadoc-error.xml

Part of https://github.com/checkstyle/checkstyle/pull/16946

Config: Introduced new check PatternVariableAssignment

---

appveyor.yml
devops/docker/README.md

Issue #951: Migrate Repo to jdk17

---

patch-diff-report-tool/src/test/java/com/github/checkstyle/internal/AbstractTest.java

Needed for https://github.com/checkstyle/checkstyle/pull/17575 to pass CI check.

Remove unnecessary parentheses

---

devops/docker/no-exception-build-image/jdk-17-groovy-git-mvn-ant-jq/Dockerfile

Issue #957: Updated Docker Script to latest Groovy version

---

devops/docker/idea-image/Dockerfile

Issue #963: Upgrade Idea Docker Script to Jdk21

---

devops/docker/no-exception-build-image/jdk-21-groovy-git-mvn-ant-jq/Dockerfile

Issue #963: Migrate Docker Script to jdk21

---

devops/docker/idea-image/Dockerfile

Issue #966: Migrate IDEA version Image to 2025.2
