checkstyle/contribution

- checkstyle-tester/pom.xml
Release Notes - Apache Maven Checkstyle Plugin - Version 2.16
Bug
* [MCHECKSTYLE-295] Test resources are not included
* [MCHECKSTYLE-271] checkstyle plugin fails with default ruleset and checkstyle 6.2
Improvement
* [MCHECKSTYLE-290] add a history table to show which version of Chesktyle is used by default in which version of m-checkstyle-p
* [MCHECKSTYLE-284] Remove config/sun_checks.xml and use the one built into Checkstyle 6.2+
* [MCHECKSTYLE-272] Upgrade to Checkstyle 6.2
Task
* [MCHECKSTYLE-285] Remove config/maven_checks.xml by removing the dependency on maven-shared-resources:2
* [MCHECKSTYLE-278] Require Java 7
* [MCHECKSTYLE-268] Add flag/option to use built-in Google style
> Update Maven Checkstyle Plugin to 2.16. #7

- qulice/qulice-checks.xml
There are many false-positives because of previous regexp.
For example:
```java
/** @return value */
```
or
```java
/**
* @author Asd asd
*/
```
> Issue #1566: Edited regexp in qulice config

- qulice/qulice-checks.xml
Weird Check that warns on multiline comments and generics:
```java
38  public abstract class AbstractOptionCheck<T extends Enum<T>>
```
or
```java
315         /*
316          * Remember: The lines number returned from the AST is 1-based, but
317          * the lines number in this array are 0-based. So you will often
318          * see a "lineNo-1" etc.
319          */
```
> 'Line cannot end with this symbol' Check has been commented out from qulice-config

- checkstyle-tester/checks-nonjavadoc-error.xml
File cleanup was forced by .editorconfig style that prohibits trailing whitespace. Moreover, typos were fixed.
> Issue #37: Disable Javadoc checks in nonjavadoc config and cleanup file

- releasenotes-xdoc-builder/src/main/java/com/github/checkstyle/ReleaseNotesMessage.java
- releasenotes-xdoc-builder/src/main/resources/com/github/checkstyle/templates/thymeleaf.template
@romani 
From mail-list:
1)
```
First line indentation is missed, generated :
"<section name="Release 6.13">
<p>Breaking backward compatibility:</p>
<ul>
<li>"
should be 
"    <section name="Release 6.13">
<p>Breaking backward compatibility:</p>
<ul>
<li>
"
```
2) Empty blank lines 
1 and 2 are Thymeleaf engine problems. I have not found the solution yet.
The only thing I can do is reformatting thymeleaf template, but it will damage readability.
> [releasenotes-xdoc-builder] minor fixes

- javadoc-expected-tree-generator/ExpectedParseTreeGenerator.java
[Previous pull-request](https://github.com/checkstyle/contribution/pull/39) is closed, I don't know what happened, I didn't press "Close".
>romani  commented 8 days ago  
>1) please apply this this file checkstyle_checks.xml , formatting is weird.
>2) "/htmlTags/OneSimpleHtmlTag.txt"
>I do not see this file. It is not clear how to use this java class.
>3) Please extend Javadoc to clearly state a reason of this file. And how it should be used.
1) Done
2) and 3) Javadoc comment has been extended.
Also, I fixed the generator to generate code with readable variable names (it was use to generate this pull-request https://github.com/checkstyle/checkstyle/pull/2643)
> ExpectedParseTreeGenerator. Useful for generating testing parse tree for Javadoc comments

- releasenotes-xdoc-builder/src/main/java/com/github/checkstyle/NotesBuilder.java
```.*``` changed ```(.|\n)*``` because some commits can contain new line character in the middle of the message. For example, ```infra: releasenotes build\n\ndebug on Travis\n```. See https://github.com/checkstyle/checkstyle/commit/00c9e7cd081b82a3cd75aacf470d5b4b718da747
> minor: [releasenotes-xdoc-builder] exclude commits that are starting with "minor|infra"

- releasenotes-xdoc-builder/pom.xml
- releasenotes-xdoc-builder/src/main/java/com/github/checkstyle/TemplateProcessor.java
- releasenotes-xdoc-builder/src/main/resources/com/github/checkstyle/templates/thymeleaf.template
1) Themyleaf version was updated to 3.0.0.BETA01 and as a result problem with indentation of the first line in output file has been resolved.
2) Made refactoring of TemplateProcessor to use more abstract class as template resolver and exclude unnecessary instantiation of String object.
3) Reformated thymeleaf template to resolve the problem with blank lines in output file which are violated by Checkstyle. I tried to save readability of template.
4) Please rename https://github.com/checkstyle/checkstyle/commit/89cee419943977af6e70264a10c669a4c29bf830 if you want it to be excluded from release notes.
> [release-notes-xdoc-builder] minor fixes and refactoring

- checkstyle-tester/launch_ahsm.sh
This is a little script to automate more of launcher with ahsm against multiple external projects.
It will save all results on external projects for later examination or pushing.
It only takes 1 parameter, the name of the branch (without any remote name). The file contains multiple variables on the top that must be customized.
It will:
1) make sure your repository is up to date (can be disabled if github is down)
2) checks out and installs master
3) runs "launch" on checkstyle-master. (minimize can be disabled)
4) checks out and installs the PR branch specified by the one parameter.
5) runs "launch" on checkstyle-pr
6) runs ahsm on all saved sites from the 2 "launch" runs
Contribution isn't updated/reset so you can customize it for the run before hand.
Downloaded external repos are …
> launch_ahsm.sh

- patch-diff-report-tool/README.md
- patch-diff-report-tool/pom.xml
- patch-diff-report-tool/src/main/java/com/github/checkstyle/FilesystemUtils.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleRecord.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/ParsedContent.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/Severity.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/StatisticsHolder.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/StaxParserProcessor.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/JxrDummyLog.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
- patch-diff-report-tool/src/main/resources/maven-base.css
- patch-diff-report-tool/src/main/resources/maven-theme.css
This is initial implementation of patch-diff-report-tool, it creates difference report from 2 different checkstyle-result.xml files. It satisfies  <a title="Checkstyle XML Diff reports tool " href="https://github.com/checkstyle/contribution/issues/50" class="issue-link js-issue-link" data-id="124509767" data-error-text="Failed to load issue title" data-permission-text="Issue title is private">checkstyle/contribution#50</a>.
Here is <a href="http://attatrol.github.io/diff_tool_example/site.html">an example of the report.</a>
The issues:
1. it still uses modified maven style;
2. generation of xdocs and xrefs is a huge issue, i'll spend next couple of days solving it, happy to get any advice here, i want to know which tool did this for checkstyle site previously.
3. assuming xdoc generation …
> add patch-diff-report-tool

- patch-diff-report-tool/README.md
- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
there's a bug at `com.github.checkstyle.Main` L207:
```
.resolve("XMLDiffGen_report_" + new SimpleDateFormat("yyyy.MM.dd_HH:mm:ss")
```
It is illegal to have ':' in windows path.
change it to '_'
> [patch-diff-report-tool] Correct path for windows

- patch-diff-report-tool/src/main/java/com/github/checkstyle/FilesystemUtils.java
Eclipse reported this as a warning when I imported the project. `readBytes` isn't used in the method.
I didn't confirm this is an actual issue but you should only write what you read. If `readBytes` is less than `BUFFER_SIZE`, `out` will be writing garbage data.
> patch-diff-report-tool: fixed possible overflow issue in resource copy

- checkstyle-web-tester/README.md
- checkstyle-web-tester/checkstyle.php
- checkstyle-web-tester/checkstyle_report.js
- checkstyle-web-tester/download-nightly.sh
- checkstyle-web-tester/download-release.sh
- checkstyle-web-tester/jquery-linedtextarea.css
- checkstyle-web-tester/jquery-linedtextarea.js
Not to be confused with `checkstyle-tester` for regression, web tester is just a simple web interface for checkstyle. Users can supply config, code, and CS version and run it. Links are generated for the file and config for easy sharing. You can select any installed CS release for regression.
Textarea fields have line numbers so its easy to see what line violations point to.
**Live version may be found here: http://rveach.no-ip.org/checkstyle/checkstyle.php**
You may use this as you wish, but I can't guarantee uptime or how long files will be saved, if you use that feature. Max 5kb limit for all files.
Releases and nightlies have to be manually installed.
> checkstyle-web-tester: added first release

- checkstyle-tester/projects-to-test-on.properties
Apache Struts 2 web framework is a free open-source solution for creating Java web applications. Apache team no longer supports Struts 1, but Apache Struts 2 contains a lot of legacy code. The code is also packed with annotations (Injections, ets) and will be good choice for testing Checkstyle's annotation checks.
https://github.com/apache/struts
> checkstyle-tester: Add Apache Struts into projects-to-test-on.properties

- .gitignore
- checkstyle-tester/launch.groovy
Implemented Checkstyle report generation script in Groovy.
Report folder diff (shell vs Groovy implementation):
script cli args example:  ```groovy launch -c my_check.xml -p projects-to-test-on.properties```
Should I update README to explain how to use the new script?
> Issue #51: Implement Checkstyle report generation script in Groovy

- releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java
@romani 
Lambda parameter 'revCommit' should be used in a condition to find the value in a stream using filter.
> minor: [releasenotes-builder] fix wrong reference in lambda expression

- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/Statistics.java
Every diff run was showing base files as exactly 3x as patch files. Running `diff` on both directories showed they were the same, so bug was in the code.
Why 3x: Utility runs once against base, which increased doubled the count. When utility runs against patch, it increases the count one more time. Thus this results in 3x.
> minor: fixed bug that tripled base file number

- checkstyle-tester/pom.xml
This is a fix for the issue described in https://github.com/checkstyle/checkstyle/issues/3704 .
Even with `haltOnException` turned off, checkstyle still prints "exception violations" as errors and causes `maven-checkstyle-plugin` to fail and `jxr` to stop the build and produce no reports during regression. There is no way to override the severity of "exception violations" through checkstyle at the moment to change them to non-errors, as the above issue won't be approved. The whole reason of adding `haltOnException` was so exceptions in regression won't trigger a stopping of regression and reporting, and so we can include exceptions in our difference reporting.
There is a fix for `maven-checkstyle-plugin` which is what this PR does. It stops `maven-checkstyle-plugin` from failing on any …
> minor: turn off failsOnError for regression

- checkstyle-tester/README.md
@romani 
@Vladlis faced problem in running diff.groovy due to the fact that AntBuilder class was intoduce in Groovy 2.4.8 but he used Groovy 1.X.X runtime
> [checkstyle-tester] doc: Add min required Groovy runtime version in README.md

- checkstyle-tester/README.md
- checkstyle-tester/diff.groovy
- checkstyle-tester/launch.groovy
- patch-diff-report-tool/README.md
#152 
1) Added property 'failsOnError' for launch.groovy as a cli option. Default value is false as I used CliBuilder from Groovy SDK. 
```
usage: groovy launch.groovy [options]
options:
-c,--checkstyleCfg <path>      Path to checkstyle config file (required)
-e,--failsOnError              Turn on 'failsOnError' of Maven Checkstyle Plugin (optional, default is false)
-l,--projectsToTestOn <path>   Path to file which contains projects to test on (required)
```
2) Performed refactoring of launch.groovy. Deleted odd validations and replaced them with default validations from CliBuilder. Validation error message which will be thrown if 'projectsToTestOn' is not specified :
```
error: Missing required option: l
usage: groovy launch.groovy [options]
options:
-c,--checkstyleCfg <path>      Path …
```
> Issue #152: Add property 'ignoreExceptios' for launch.groovy

- patch-diff-report-tool/README.md
- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CliPaths.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
Issue #82
added option `shortFilePaths`.
Utilities that call patch-diff-report still need to be updated.
> Issue #82: added option 'shortFilePaths' to patch-diff-report-tool

- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffReport.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/Statistics.java
- patch-diff-report-tool/src/main/resources/header.template
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmpty.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmptyWithConfig.html
- patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
Issue #88
Fields and IDs were named uniqueMessagesBase and uniqueMessagesPatch.
Let me know if there is a better name.
This section will only show counts of messages in reports.
Example: 
[Normal way says 7](https://github.com/rnveach/contribution/blob/945f2734c2ced12d6458214563b4146cd205e9e8/patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html#L213), which is all violations in file.
[True count in report is 6](https://github.com/rnveach/contribution/blob/945f2734c2ced12d6458214563b4146cd205e9e8/patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html#L235).
> Issue #88: added base/patch unique message counts

- checkstyle-tester/launch.groovy
#193 
[createNewFile](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createNewFile--) method creates new file only if the file does not exist.
> Issue #193: Fix FileAlreadyExistsException in launch.groovy

- checkstyle-tester/README.md
This is so I can link to the section directly.
> minor: change tester deploy to a link

- checkstyle-tester/projects-for-wercker.properties
- checkstyle-tester/projects-to-test-on.properties
When testing locally, run on checkstyle took 7 minutes.
When I removed `test/resources` it only took 30 seconds.
I found this slowdown to be `InputAllEscapedUnicodeCharacters` which we just recently added. I assume JXR has some issue with it because of it's size.
> minor: removed large file from regression to prevent slowdown

- checkstyle-tester/README.md
- checkstyle-tester/my_check.xml
#200
It default config is not changed we will get the following diff report:
Sorry, but my IDEA continues reformatting blank lines with tabs even if I disable code formatting before a commit.
> Issue #200: Edit default config for checkstyle tester to produce no violations

- releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java
#208 
@romani 
> This looks like the issue. Binary search returns >= 0 if it exists in array and < 0 on where it should be inserted into array if it doesn't exist. It doesn't guarantee a result of -1 all the time.
Condition should be checking >= 0 instead of != -1.
Yes, that was the problem.
> issue checkstyle/checkstyle#3437
one more : checkstyle/checkstyle#3892
has label "new feature" but it is not present in releasenotes after 7.6, that forced me to create 7.6.1 release instead of 7.7 .
TODO: investigate a reason of missed "new feature" group in release notes of 7.6.1 - checkstyle.sourceforge.net/releasenotes.html#Release_7.6.1
Fixed.
> one more problem - checkstyle/checkstyle#3329 does not have label and build is not failed
Fixed.
> link to all closed "new feature" issues - …
> Issue #206: Fix incorrect filter condition for binary search

- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_thymeleaf.template
#205 
Release notes after fix:
[xdoc.xml](http://mezk.github.io/i204-fix-xdoc-template/xdoc.xml)
[xdoc.html](http://mezk.github.io/i204-fix-xdoc-template/xdoc.html)
Due to usage of ```<th: block>``` there are blank lines in release notes: (xdoc.xml)
```
<li>
Revert &quot;Pull #3162: Update version of commons-collections to 3.2.2 to fix security vulnerability CVE-2015-6420&quot;. Author: Roman Ivanov
</li>
```
and I cannot find workaround for these issues. There was [the request](https://github.com/thymeleaf/thymeleaf/issues/108) to implement the functionality to remove blank lines, however it was declined.
@romani 
Please, recheck. This is the cli args that I used to generate reports:
```-localRepoPath /checkstyle -startRef 2b90c7db5b6e64c7e667d112b982f865e5e9aa40 -githubAuthToken …
```
> Issue #204: Fix xdoc_thymeleaf.template to avoid spaces in issues links

- .travis.yml
- checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
- checkstyle-tester/launch.groovy
#219 
1) Fixed regexp and problem with one line reports.
2) Replaced ArrayList with HashSet to avoid file path duplication in getFilesReferencedInReport result as index.html (checkstyle.html) can contain more than one reference to the same file.
**FYI**
The code will collect all matching substrings of the line applying the given transformer closure (```it.substring(xrefStartIdx)```):
```java
matcher.collect { it.substring(xrefStartIdx) }
```
I prepared two reports which I used for testing:
https://github.com/MEZk/mezk.github.io/tree/master/i219-launch-groovy-bug
@romani 
Codenarc panics :D
See https://travis-ci.org/checkstyle/contribution/jobs/226174048
One of the violations which references my changes:
```
Violation: Rule=UnnecessarySubstring P=3 Line=270 Msg=[Violation in class None. …
```
> Issue #219: Fix bug when launch.groovy cannot handle reports with links all on 1 line

- .travis.yml
- checkstyle-tester/launch.groovy
Issue #223
Tested locally on a bad URL.
````
$ groovy ./launch.groovy --listOfProjects fail.properties --config checks-nonjavadoc-error.xml
Testing Checkstyle started
Cloning git repository 'BAD' to repositories/BAD folder ...
Cloning into 'repositories/BAD'...
fatal: unable to access 'https://BADCANTRESOLVETHIS.com/google/guava/': Failed to connect to BADCANTRESOLVETHIS.com port 443: Connection timed out
Cloning into 'repositories/BAD'...
fatal: unable to access 'https://BADCANTRESOLVETHIS.com/google/guava/': Failed to connect to BADCANTRESOLVETHIS.com port 443: Connection timed out
Cloning into 'repositories/BAD'...
fatal: unable to access 'https://BADCANTRESOLVETHIS.com/google/guava/': Failed to connect to BADCANTRESOLVETHIS.com port 443: Connection timed out
Cloning into …
```
> Issue #223: changed launch to try cloning multiple times

- .travis.yml
- checkstyle-tester/LAUNCH_GROOVY_README.md
- checkstyle-tester/README.md
- checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
- checkstyle-tester/diff.groovy
issue #213 
1) Added ability to generate Checkstyle reports for patch branch only with diff.groovy
2) Extended README.md
3) diff.groovy does not have ```-i``` command line option (only launch groovy has), so it was removed from Travis CI yml.
Further refactoring and performance optimization of diff.groovy will be performed in the scope of https://github.com/checkstyle/contribution/issues/182.
diff.groovy should be renamed to reports.groovy or something similar in separate issue.
@rnveach
Maybe we need to have the manual for launch.groovy in a separate file. Do contributors need to know about it from the main REAMDE.md of checkstyle-tester?
> Issue #213: checkstyle-tester: support regression on new checks/tokens

- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleConfigurationsParser.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
- patch-diff-report-tool/src/main/resources/content.template
- patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
- patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
- patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
- patch-diff-report-tool/src/test/resources/InputPatchReportNonCompilable.xml
- patch-diff-report-tool/src/test/resources/run/NonCompilable.java
Minor removes unused exceptions and parameters.
Issue #226
Since the file is non-compilable and the HTML file will be garbage, the report now has no link for the file in question.
> Issue #226: fixed NPE from non-compilable file in patch-diff-report-util

- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffReport.java
- patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
Fixed issue where empty files were being displayed in patch only report. This polluted the report with too many headers in a real scenario.
See http://rveach.no-ip.org/checkstyle/regression/reports/30/checkstyle/index.html
Fix ignores files with no violations. Test regression shows it only affects patch only report with less numbers and headers. It doesn't affect the overall file number count.
Will rename commit to reference this pull number.
> minor: removed empty files with no violations from patch only report

- patch-diff-report-tool/src/main/resources/header.template
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmpty.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmptyWithConfig.html
- patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
- patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
- patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
Issue #222
Renamed all `Unique Rows` to `Violations`.
> Issue #222: renamed rows to violations in patch-diff-report-tool

- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
Removes `View Javadoc` that is always found at the top of the xref view, as it is an invalid link and it never works.
Example:
http://rveach.no-ip.org/checkstyle/regression/reports/30/checkstyle/xref/checkstyle/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/InputVariableDeclarationUsageDistanceCheck.java.html
http://rveach.no-ip.org/checkstyle/regression/reports/30/checkstyle/xref/checkstyle/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/InputVariableDeclarationUsageDistanceCheck.html
> minor: removed javadoc link from patch-diff-report xref

- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/TextTransform.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/XrefGenerator.java
- patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
- patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
- patch-diff-report-tool/src/test/resources/ExpectedXrefNonCompilable.html
Issue #240
Copied `JavaCodeTransform`, trimmed it down to remove Java related stuff, and made it pass checkstyle.
Added a test to show what the output of `TextTransform` will look like.
I question if we should just remove JXR completely, but it does bold keywords and such which is slightly nice.
> Issue #240: added support for xrefs that fail JXR

- releasenotes-builder/pom.xml
- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_thymeleaf.template
- releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_all_sections.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_breaking_compatibility_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_bug_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_new_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_notes_section.txt
issue #243 
Fixed thymeleaft template to have it formatted correct in case freemarker has problems. I'll switch the tool to freemarker in the next PR.
Template looks wired, but works.
> Issue #243: Fix thymeleaf template to avoid incorrect placement of '\n'

- checkstyle-tester/launch_diff_antlr.sh
- checkstyle-tester/launch_diff_variables.sh
Issue #237
Very similar to the layout of my other script.
Runs checkstyle's `-J` option on all java files in a project. It does 2 files in parallel, base and patch.
This produces java and javadoc trees so we can compare all ANTLR in one script.
I left a `echo "$f"` display in the code to verify where the script is in it's progress because of how long it takes to do an entire project.
Checkstyle: 34 minutes
Sevntu: 3 minutes
guava: 26 minutes
> Issue #237: added antlr regression script

- checkstyle-tester/checks-nonjavadoc-error.xml
We can enable config for `validateOnlyOverlapping` in `RequireThis` based on fix at https://github.com/checkstyle/checkstyle/pull/4859#issuecomment-319543930
> config: enable RequireThis with validateOnlyOverlapping

- checkstyle-tester/checks-nonjavadoc-error.xml
This PR is being created because of a backward breaking change being made in CheckStyle.
PR: checkstyle/checkstyle#4893
Issue: checkstyle/checkstyle#3671
We are breaking multiple APIs in Checkstyle 8 to clean up deprecated methods and such. This removed the deprecated property maxLineLength in LeftCurly as it wasn't doing anything and it's functionality was removed some time ago.
> config: removed maxLineLength in LeftCurlyCheck

- checkstyle-tester/launch_diff.sh
- checkstyle-tester/launch_diff_variables.sh
To show how https://github.com/checkstyle/contribution/issues/273 should be done, I updated my own script to not rely on maven anymore.
It uses the pure Checkstyle CLI with no updates to patch-diff-report-tool needed and not extra dependencies.
* All `install` commands where changed to `package` now.
* `github` support was removed, should just rely on `git`.
* added extra code to prevent switching to `master` as if it was a different branch.
* added branch names and commit ids to final report like groovy scripts.
Here is an example run of the differences for the same PR and config:
Maven: http://rveach.no-ip.org/checkstyle/regression/reports/149/
CLI: http://rveach.no-ip.org/checkstyle/regression/reports/150/
Only real difference is counts for number of files being processed overall. …
> launch_diff: upgraded util to not rely on maven plugin

- .travis.yml
- checkstyle-tester/StarterRuleSet-AllRulesByCategory.groovy.txt
- checkstyle-tester/codenarc.sh
- checkstyle-tester/diff.groovy
- checkstyle-tester/launch.groovy
Running the latest stable version of CodeNarc (`1.1`) with the StarterRuleSet file caused a couple of errors:
ERROR: No such rule named [GrailsSessionReference]. . Expression: ruleClass. Values: ruleClass =     
ERROR: No such rule named [AbcComplexity]. . Expression: ruleClass. Values: ruleClass = null
This PR removes the two deprecated rules, updates the test script with CodeNarc 1.1, and fixes several warnings in the `checkstyle-tester` Groovy scripts.
<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the branch of this pull request. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest target …
> Remove deprecated CodeNarc rules

- checkstyle-tester/LAUNCH_GROOVY_README.md
- checkstyle-tester/README_OLD.md
- checkstyle-tester/launch_diff_antlr.sh
- checkstyle-web-tester/download-nightly.sh
- checkstyle-web-tester/download-sevntu-nightly.sh
- checkstyle-web-tester/download-sevntu.sh
- qulice/README.md
Issue #282 
There flag `cobertura.skip` has no effect anymore and should be replaced with `jacoco.skip`.
> Issue #282: Replace Cobertura with JaCoCo

- checkstyle-tester/LAUNCH_GROOVY_README.md
- checkstyle-tester/README_OLD.md
- checkstyle-tester/launch_diff_antlr.sh
- checkstyle-tester/projects-for-wercker.properties
- checkstyle-tester/projects-to-test-on.properties
- checkstyle-web-tester/download-nightly.sh
- checkstyle-web-tester/download-sevntu-nightly.sh
- checkstyle-web-tester/download-sevntu.sh
- qulice/README.md
- qulice/projects-to-test-on.properties
Issue #284
Flag `findbugs.skip` replaced with `spotbugs.skip`.
Finbugs repo in the congif file projects-to-test-on.properties replaced with Spotbugs.
> Issue #284: Replace Findbugs with Spotbugs

- releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java
issue #286
result will be 
```
Notes:
Revert config: bump pmd plugin to 3.9.0 version
Drop findbugs
Replace java.awt.event.InputEvent#getModifiers() with getModifiersEx()
```
> Issue #286: fix for crash on incorrect Revert

- checkstyle-tester/projects-to-test-on.properties
Since JDK10 is released, we need to start using it for regression testing.
> config: Add jdk10 repo to projects-to-test-on.properties

- checkstyle-tester/sevntu_launch_diff.sh
Like checkstyle one, it doesn't use maven.
To run sevntu easily, I have it copy itself over to Checkstyle repo and package it that way.
I recently had to update this check to only use release version of checkstyle as master contains backwards breaking changes that conflict with sevntu's current checkstyle version.
Otherwise there is not much difference between this util and the checkstyle one.
> sevntu_launch_diff: added sevntu difference utility

- releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
- releasenotes-builder/src/main/java/com/github/checkstyle/TemplateProcessor.java
- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
- releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java
Issue #309
It is a required field, so we should allow it to be used in templates.
> Issue #309: allow remote repository path variable in freemarker

- releasenotes-builder/src/main/java/com/github/checkstyle/NotesBuilder.java
Issue #289 .
Changed detection from `"` on end of commit message to just having 2 `"`.
Verified locally with `-localRepoPath M:\checkstyleWorkspace\checkstyle -remoteRepoPath checkstyle/checkstyle -startRef checkstyle-8.8 -endRef checkstyle-8.9 -releaseNumber 8.9 -generateXdoc`.
> Issue #289: fix revert commit detection for releasenotes

- releasenotes-builder/config/import-control.xml
- releasenotes-builder/src/main/java/com/github/checkstyle/TemplateProcessor.java
- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
- releasenotes-builder/src/test/java/com/github/checkstyle/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_all_sections.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_breaking_compatibility_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_bug_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_new_section.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/correct_notes_section.txt
Issue #320
Patch to main repo:
````
diff --git a/src/site/resources/css/site.css b/src/site/resources/css/site.css
index f77781f..da6cf05 100644
--- a/src/site/resources/css/site.css
+++ b/src/site/resources/css/site.css
@@ -62,3 +62,7 @@
white-space: -o-pre-wrap !important;
word-wrap: break-word !important;
}
+
+.releaseDate {
+  float: right;
+}
diff --git a/src/xdocs/releasenotes.xml b/src/xdocs/releasenotes.xml
index 68da3d0..b80cf9c 100644
--- a/src/xdocs/releasenotes.xml
+++ b/src/xdocs/releasenotes.xml
@@ -16,6 +16,7 @@
<body>
+    <div class="releaseDate">7/2/2018</div>
<section name="Release 8.11">
<p>Breaking backward compatibility:</p>
<ul>
@@ -91,6 +92,7 @@
</ul>
</section>
+    <div class="releaseDate">7/1/2018</div>
<section name="Release 8.10.1">
<p>Bug fixes:</p>
<ul>
```` …
> Issue #320: add todaysDate variable to releasenotes

- checkstyle-tester/pom.xml
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/709#issuecomment-408118508 ,
> wercker
org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.github.sevntu-checkstyle:sevntu-checkstyle-maven-plugin:jar:1.30.0
> config: upgraded sevntu-checkstyle-maven-plugin to 1.30.0

- releasenotes-builder/config/intellij-idea-inspections.xml
- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
Issue #335
https://teamcity.jetbrains.com/viewLog.html?buildId=1663372&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsMaster
> src/main/java/com/github/checkstyle/github
NotesBuilder.java (1)
65: IGNORED_COMMIT_MESSAGES_PATTERN Redundant suppression
but my local Idea place violation on this code. TC status is more in priority.
> Issue #335: revert suppression as TC see it as redundant 

- checkstyle-tester/checks-nonjavadoc-error.xml
It is easy to copy and paste this configuration for regression testing. We already have a top level severity ignore, so we don't need these other ones. This allows us to change the top one without having to find ones below too.
> config: remove ignore severity property for checks

- checkstyle-tester/checks-nonjavadoc-error.xml
This is changes for checkstyle issue https://github.com/checkstyle/checkstyle/issues/5897 .
A lot of hidden checks were stated that they are javadoc and slow, but these aren't `AbstractJavadocCheck`s but 1-2 use the regular expression for javadoc but last I check those weren't slow.
> checkstyle: added missing modules to checks-nonjavadoc-error.xml

- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocAll.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
This is a follow-up fix for https://github.com/checkstyle/checkstyle/pull/6514#discussion_r262939233 where the results of the generated text had to be changed to make the site files pass validation.
> doc: move the release date div inside the section to generate valid markup

- checkstyle-tester/launch.groovy
When I batch-added all my 170 locally available projects, there were some without Java files.
For those no report was generated and then the removeNonReferencedXrefFiles step failed with FileNotFoundException.
With this change, this is simply ignored.
> checkstyle-tester: do not fail if analysed project does not contain Java files because no report is present then

- checkstyle-tester/diff.groovy
1. add a title to the report diff summary page
2. add tested projects count to report diff summary
3. add checkstyle favicon to report diff summary
4. clear report diff summary if it exists already
5. sort report diff summary, projects with differences first, case-insensitive alphabetical within the two sections
6. add total found differences to report diff summary
> Report Diff Summary Improvements

- checkstyle-tester/LAUNCH_GROOVY_README.md
- checkstyle-tester/README.md
- checkstyle-tester/README_OLD.md
- checkstyle-tester/pom.xml
Issue #394 
`sevntu-checkstyle-maven-plugin` was replaced with `sevntu-checks dependency`
> Issue #394: replace sevntu-checkstyle-maven-plugin with sevntu-checks

- checkstyle-tester/checks-only-javadoc-error.xml
Add `JavadocBlockTagLocation` check to `checks-only-javadoc-error.xml`
reference: checkstyle/checkstyle#6929
> config: added JavadocBlockTagLocationCheck

- checkstyle-tester/README.md
- checkstyle-tester/checks-import-order/projects-to-test-imports-guava.properties
- checkstyle-tester/checks-import-order/projects-to-test-imports-java-design-patterns.properties
- checkstyle-tester/projects-for-circle.properties
- checkstyle-tester/projects-for-travis.properties
- checkstyle-tester/projects-for-wercker.properties
- checkstyle-tester/projects-to-test-on.properties
Updated and re-organized the read me so it flows better. Add specific sections for new things like special configs and split existing sections into their own unique section and added a specific order to the document.
Some minor things may have been removed, but for the most part everything is still there, just re-ordered and with some new wording.
> doc: update and re-organize checkstyle-tester read me

- checkstyle-tester/pom.xml
- checkstyle-tester/projects-for-wercker.properties
Issue checkstyle/checkstyle#3279
fix in pom is required to avoid problem with jxr plugin that try to parse all files:
```
✘-1 ~/java/github/romani/checkstyle/.ci-temp/contribution/checkstyle-tester [master|✚ 3] 
$ mvn -X -e --batch-mode site -Dcheckstyle.config.location=checks-nonjavadoc-error.xml -Dcheckstyle.excludes=**/.ci-temp/**/*,**/resources-noncompilable/**/*,**/InputAllEscapedUnicodeCharacters.java
....
[DEBUG] parsing... local-checkstyle/.ci-temp/contribution/patch-diff-report-tool/src/test/resources/run/PatchOnly2.java
[DEBUG] parsing... local-checkstyle/.ci-temp/contribution/patch-diff-report-tool/src/test/resources/run/Same1.java
[DEBUG] parsing... local-checkstyle/.ci-temp/contribution/patch-diff-report-tool/src/test/resources/run/NonCompilable.java
[INFO] …
```
> Issue checkstyle/checkstyle#3279: introduction of diff regression local-checkstyle

- releasenotes-builder/pom.xml
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-472980
detected at https://app.snyk.io/org/checkstyle/project/6464a1a8-78eb-4b93-aa92-c6889786636a?utm_campaign=vuln_alert&utm_medium=email&utm_source=Project&fromGitHubAuth=true
https://github.com/github-api/github-api/pull/575#event-2731051465
> config: bump jackson-databind to 2.10.0 to avoid security alert

- checkstyle-tester/checks-nonjavadoc-error.xml
chekcstyle PR for checkstyle/checkstyle#7329 is merged 
it is problem at https://ci.appveyor.com/project/Checkstyle/contribution/builds/29688263/job/uocbc27m1d0j5lx3#L357
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site
(default-site) on project sample: Error during page generation: Error rendering
Maven report:
Failed during checkstyle configuration: cannot initialize module TreeWalker -
cannot initialize module JavadocMethod - Property 'allowUndeclaredRTE' 
does not exist,
please check the documentation -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample:
Error during page generation
at …
```
> checkstyle/checkstyle#7329: remove deprecated properties from JavadocMethod

- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
it is hard to find example of build failure as i usually fix such failures quickly.
but it will be helpful.
Example of WARN - https://travis-ci.org/checkstyle/checkstyle/jobs/630142958#L550
testing:
```
This reverts commit 1ed4da5951284a3f92a42f96edc7d74f6785658f.
[WARN] Issue #5777 "Update AbstractChecks to log DetailAST (part3)" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/5777
[WARN] Issue #6916 "Upgrade to junit 5" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/6916
[WARN] Issue #7380 "JavadocMethod: missed throws tag for throw in method body" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/7380
Execution succeeded!
```
> minor: releasenotes-builder: print link to issue to ease navigation from logs to issue

- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
- patch-diff-report-tool/src/main/resources/content.template
- patch-diff-report-tool/src/main/resources/header.template
- patch-diff-report-tool/src/main/resources/site.css
- patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
- patch-diff-report-tool/src/test/resources/ExpectedReportConfigMessages.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferences.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesRefFiles.html
- patch-diff-report-tool/src/test/resources/ExpectedReportDifferencesShortFilePaths.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmpty.html
- patch-diff-report-tool/src/test/resources/ExpectedReportEmptyWithConfig.html
- patch-diff-report-tool/src/test/resources/ExpectedReportMessages.html
- patch-diff-report-tool/src/test/resources/ExpectedReportNonCompilable.html
- patch-diff-report-tool/src/test/resources/ExpectedReportPatchOnly.html
- patch-diff-report-tool/src/test/resources/ExpectedReportSeverities.html
- patch-diff-report-tool/src/test/resources/ExpectedReportTextMode.html
Issue #426
building on top of @romani's branch 426-wrap (#427). 
For improved readability I suggest making tables horizontal scrollable like we did for checkstyle documentation. 
Changes are uploaded to https://jo2.github.io/checkstyle-contribution/
> Issue #426: add fix for chrome

- checkstyle-tester/projects-for-circle.properties
- checkstyle-tester/projects-to-test-on.properties
From https://github.com/checkstyle/checkstyle/issues/3236#issuecomment-578417379 - removing TypeUseTarget.java from the excluded files for the JDK projects since it can be parsed after https://github.com/checkstyle/checkstyle/pull/7407
> config: remove TypeUseTarget from excludes

- .ci/travis.sh
this PR is passing, unfortunately on local maven does not skip incompilable files and execution is failing, even maven is instructed to ignore exceptions
I can run regression only with code changes like (`--ignoreExcludes` is removed):
```
✔ ~/java/github/checkstyle/contribution/checkstyle-tester [config-error L|✚ 2…1] 
$ git diff
diff --git a/checkstyle-tester/diff.groovy b/checkstyle-tester/diff.groovy
index e913dce..5b07293 100644
--- a/checkstyle-tester/diff.groovy
+++ b/checkstyle-tester/diff.groovy
@@ -185,7 +185,7 @@ def generateCheckstyleReport(cfg) {
executeCmd("mvn --batch-mode -Pno-validations clean install", cfg.localGitRepo)
executeCmd("""groovy launch.groovy --listOfProjects $cfg.listOfProjects
-            --config $cfg.checkstyleCfg --ignoreExceptions --ignoreExcludes …
```
> infra: use checkstyle project (at it has incompilable files) for diff.groovy

- patch-diff-report-tool/pom.xml
- releasenotes-builder/pom.xml
Identified at https://github.com/checkstyle/checkstyle/pull/7706#issuecomment-592980127 .
We need to allow these 2 projects to override the default checkstyle config location for regression.
> minor: allow overriding checkstyle config location

- checkstyle-tester/pom.xml
This PR will upgrade maven-checkstyle-plugin to 3.1.1 for Checkstyle's regression testing.
Related to Issue:
Issue: checkstyle/checkstyle/issues/7190
PR: checkstyle/checkstyle#7778
> minor: upgrade maven-checkstyle-plugin

- checkstyle-tester/checks-only-javadoc-error.xml
Add `JavadocMissingWhitespaceAfterAsteriskCheck` check to `checks-only-javadoc-error.xml`
reference: checkstyle/checkstyle#7775
> config: added JavadocMissingWhitespaceAfterAsteriskCheck

- checkstyle-tester/launch.sh
- checkstyle-tester/projects-to-test-on.properties
reason: https://github.com/checkstyle/checkstyle/pull/8085#issuecomment-621894699
github has mirrors only for 11-14 jdk.
> minor: change recent jdk to use github mirrors to make it more stablefor download

- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CliPaths.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleReportsParser.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/EmptyXmlEventReader.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
- releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
- releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
- releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
- releasenotes-builder/src/main/java/com/github/checkstyle/globals/Constants.java
- releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
- releasenotes-builder/src/main/java/com/github/checkstyle/globals/Result.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/MailingListPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/SourceforgeRssPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/TwitterPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/XdocPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/templates/TemplateProcessor.java
According to https://checkstyle.sourceforge.io/config_javadoc.html#JavadocParagraph
> There is one blank line between each of two paragraphs and one blank line before the at-clauses block if it is present.
Unfortunately, this check is not working yet in checkstyle, so many of these violations sneaked into the repository, but it's coming in https://github.com/checkstyle/checkstyle/pull/7932 .
I wrote a script to apply the missing newline violations from mvn verify. It is available here: https://github.com/josephmate/FixAtClauseError
> minor: fix violations from RequireEmptyLineBeforeAtClauseBlock

- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/XdocPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/templates/TemplateProcessor.java
Similar to https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/816, this is a PR to fix failing CI in checkstyle/checkstyle#8213.
These are Checkstyle violations that were previously not detected due to issue checkstyle/checkstyle#8117.
> minor: fix violations from JavadocMethod

- checkstyle-tester/diff.groovy
Issue #431: add timestamp to diff.groovy main report
Instead of adding timestamp next to SHA,  I made a new line.  This will make the timestamp easier to read, and since I thought the time zone was a relevant addition, the line would have been too long if printed next to SHA.
Example report:
> Issue #431: add timestamp to diff.groovy main report

- checkstyle-tester/diff.groovy
Missed in #488, we needed to add report generation time to index.html
> minor: add report generation time to diff.groovy (#431)

- misc/jdk14-test-files.list
Related to https://github.com/checkstyle/checkstyle/pull/8634, this file is to be used for testing Checkstyle's ability to parse openjdk14 test files, mostly from `jdk14/test/langtools/tools/`.  Sourced from https://download.java.net/openjdk/testresults/14/archives/36/langtools-36-summary.txt .
> minor: add openjdk14 testing files list

- checkstyle-tester/checks-only-javadoc-error.xml
Add RequireEmptyLineBeforeAtClauseBlock check to checks-only-javadoc-error.xml
reference: checkstyle/checkstyle#7932
> config: added RequireEmptyLineBeforeBlockTagGroup

- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffReport.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/parser/CheckstyleTextParser.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
From https://github.com/checkstyle/checkstyle/pull/8766#issuecomment-681989527:
> from wercker:
```
[INFO] --- maven-checkstyle-plugin:3.1.1:check (check) @ patch-diff-report-tool ---
[INFO] There are 4 errors reported by Checkstyle 8.36-SNAPSHOT with ../../../config/checkstyle_checks.xml ruleset.
[ERROR] src/main/java/com/github/checkstyle/parser/CheckstyleTextParser.java:[176,36] (naming) IllegalIdentifierName: Name 'record' must match pattern '(?i)^(?!(record|yield|var)$).+$'.
[ERROR] src/main/java/com/github/checkstyle/parser/CheckstyleTextParser.java:[222,32] (naming) IllegalIdentifierName: Name 'record' must match pattern '(?i)^(?!(record|yield|var)$).+$'.
[ERROR] src/main/java/com/github/checkstyle/data/DiffReport.java:[132,31] (naming) IllegalIdentifierName: Name 'record' must …
```
> minor: rename all instances of "record" as identifier to "checkstyleRecord"

- checkstyle-tester/launch.groovy
- checkstyle-tester/pom.xml
Issue #530: Remove JXR library from launch.groovy
Ok, I wanted to provide as much proof as possible that this change has no ill effects; please let me know what else I can show. 
First, a simple example using two repos that I created (note that my `zsh` prompt shows the branch that I am currently on, as well as my notes).
One has non-compilable code that should cause exception (`broken-repo`) and one has compilable code (`not-broken`) that should( and does) allow for a `checkstyle-results.xml` to be generated: https://gist.github.com/nmancus1/d097e9654130329200849742ccf0971c
If anyone would like to verify the above, here are the projects file lines:
```
#broken|git|https://github.com/nmancus1/broken-repo.git|master||
#not-broken|git|https://github.com/nmancus1/not-broken.git|master||
``` …
> Issue #530: Remove JXR library from launch.groovy

- checkstyle-tester/README.md
- checkstyle-tester/diff.groovy
Issue #523: Add extraMvnOptions support to diff.groovy
I am going to open a PR in Checkstyle for https://github.com/checkstyle/checkstyle/issues/8960 in order to show that the arguements are passed to maven correctly.
> Issue #523: Add extraMvnOptions support to diff.groovy

- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CheckstyleRecord.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffReport.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/DiffUtils.java
- patch-diff-report-tool/src/test/java/com/github/checkstyle/DiffUtilsTest.java
Issue #532 
Originally posted as part of #521
Here is only the part about optimization. Supporting multi-core execution requires a lot of research and will be done separately.
> Issue #532: optimize DiffReport

- checkstyle-tester/projects-to-test-on.properties
Identified at https://github.com/checkstyle/checkstyle/pull/8177#issuecomment-774805912 and lots of other places, until Checkstyle can parse OpenJDK > 9, we should remove 10 and 11 so that contributors do not get confused when generating reports.
> config: remove OpenJDK repos that cause issue with regression

- checkstyle-tester/README.md
- checkstyle-tester/projects-to-test-on-for-github-action.properties
Useful for https://github.com/checkstyle/checkstyle/pull/9258
Left commented out
1. Duplicated projects with exclusion (default project list does not need duplication)
2. Open jdk repos (very heavy, can take a lot of time to create report for them)
> config: uncomment many projects in projects-to-test-on.properties

- checkstyle-tester/projects-to-test-on-for-github-action.properties
From https://github.com/checkstyle/checkstyle/pull/9760#issuecomment-810324358 and other Checkstyle PR's, OpenJDK9 has been causing problems in report generation; we should disable it for now.
> infra: remove OpenJDK9 repo from github action project file

- checkstyle-tester/projects-to-test-on-for-github-action.properties
- checkstyle-tester/projects-to-test-on.properties
Noticed at https://github.com/checkstyle/checkstyle/pull/9755?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE3NDM0OTc2ODA6MzEyNTI1MzI%3D#issuecomment-816673317
spring-integration has changed from `master` branch to `main`.
This occurred at https://github.com/spring-projects/spring-integration/pull/3539
> infra: change spring-integration master branch to main

- .ci/travis.sh
- appveyor.yml
- checkstyle-tester/LAUNCH_GROOVY_README.md
- checkstyle-tester/README.md
- checkstyle-tester/diff-groovy-regression-config.xml
- checkstyle-tester/diff.groovy
Issue #529: Deprecate launch.groovy and merge functionality into diff.groovy
Notes:
-  We should replace all usages of `launch.groovy` with `diff.groovy` in single mode, using 'patchBranch' and 'patchConfig' . This isn't a big deal, we are just saving an extra checkstyle run using `master` branch.
- Any usages of `launch` that are being replaced with `diff` that DO NOT use `-i` need to specify `--allowExcludes` now.
- All existing `diff.groovy` usage needs to be reviewed; `no-exception` tests can be done in single mode.
Related PRs that must be merged after this for CI in other projects:
https://github.com/checkstyle/checkstyle/pull/9278
https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/828
A good example of `no-exception` testing and replacing `launch.groovy` for many cases is: …
>  Issue #529: Deprecate launch.groovy and merge functionality into diff.groovy

- releasenotes-builder/src/main/java/com/github/checkstyle/github/CommitMessage.java
- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
- releasenotes-builder/src/test/java/com/github/checkstyle/github/CommitMessageTest.java
Fixes #560
The existing pattern validates the presence of "\n" at the end of the message. But this is not necessary. All messages are checked in CI.
To skip some release notes, it is enough to simply examine the beginning of the message.
All message matching code extracted to a helper class `CommitMessage`.
> Issue #560: fix stack overflow in ignore pattern

- .travis.yml
Setting JAVA_HOME to /usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
> Travis: problem with JAVA_HOME for groovy package 

- .ci/travis.sh
- .travis.yml
this PR is required for Travis support to investigate problem with long delay(by timeout eventually) in fail of build
https://app.travis-ci.com/github/checkstyle/contribution/jobs/547768471
```
README.md:1: MD002 First header should be a top level header
README.md:1: MD041 First line in file should be a top level header
A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
> config: remove 'set -e' in Travis

- devops/docker/no-exception-build-image/jdk-11-groovy-git-mvn/Dockerfile
New Docker image for checkstyle/checkstyle#9146
Based on https://hub.docker.com/layers/groovy/library/groovy/jdk11/images/sha256-42bf7a975b867ded59c87f541e58f4be60b42c2ba4840939986950da2a8f013d
> infra: Dockefile for jdk 11 groovy image

- patch-diff-report-tool/README.md
- patch-diff-report-tool/src/main/java/com/github/checkstyle/CliArgsValidator.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/Main.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CheckstyleRecord.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/CliOptions.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/data/Statistics.java
- patch-diff-report-tool/src/main/java/com/github/checkstyle/site/SiteGenerator.java
- patch-diff-report-tool/src/test/java/com/github/checkstyle/MainTest.java
Added missing documentation.
Fixed eclipse errors.
Renamed `CliPaths` to `CliOptions` since it does currently contain something that is not a path and I was thinking of expanding it for a new option. Also renamed `checkPaths` to `validate` since they aren't paths anymore. Split validate method between XML and Text for easier separation.
> Minor various fixes for diff-report-tool-util

- releasenotes-builder/config/intellij-idea-inspections.xml
based on feedback of https://teamcity-support.jetbrains.com/hc/requests/4025415
>The hanging build uses IntelliJ IDEA 2021.2.3 while the previous build was using 2020.1.1.
In TeamCity itself nothing has changed in the inspections build runner, so the issue is most likely on the IntelliJ IDEA side. I've created a ticket: https://youtrack.jetbrains.com/issue/TW-76168/IntelliJ-IDEA-2021-2-3-inspections-build-is-hanging
In the meantime try using the previous version of IntelliJ IDEA in this build.
I updated TC config to use 2020.1.1 .
it works but there are Grammar violations that we disabled in main repo - https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_ContributionIdeaInspectionsMaster/3854533?buildTab=Inspection
> config: copy config from main repo to sync on usage and config

- releasenotes-builder/README.md
- releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
- releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/github_post.template
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageAll.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
Fixes #623 
Checkstyle 10.4-SNAPSHOT - https://checkstyle.org/releasenotes.html#Release_10.4-SNAPSHOT
Bug fixes:
#11736 - MissingJavadocType: Support qualified annotation names
#11655 - Update google_checks.xml to have the SuppressionCommentFilter and SuppressWarningsHolder modules in the config by default (and by extension, SuppressWarningsFilter)
<details>
<summary>Other Changes:</summary>
<br>
Update releasenotes to use GitHub Pages execution
<br />
Allow SuppressWarningHolder to suppress the violation with NameCheck
<br />
Pitest: Kill all surviving mutations
<br />
Pitest: Activate "ALL" mutator group
<br />
Use Shellcheck to resolve violations code in Shell Script
<br />
pitest: increase mutation coverage for pitest-imports profile to 100% 
<br />
Update GitHub Action for …
> Issue #623: Add -generateGitHubPage and - githubpostTemplate arguments

- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/github_post.template
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageAll.txt
> Issue #630: releasenotes-builder: update Github template to be more compact.

- .github/workflows/bump_project_version.yml
Partially Fixes #634 
Testing: 
When version is different : [ACTION](https://github.com/Rahulkhinchi03/contribution/runs/7939630676?check_suite_focus=true)
When a version is the same: [ACTION](https://github.com/Rahulkhinchi03/contribution/runs/7939635057?check_suite_focus=true)
> Issue #634: satelite projects should use latest checkstyle as soon at is appears in maven repo

- releasenotes-builder/config/checkstyle.properties
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/README.md
> Issue #614: Resolve alphabetically unsorted properties IDEA violations

- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
#614
From `org.eclipse.jgit.lib.Repository.peel(..)` javadoc:
```java
/**                                                                          
* Peel a possibly unpeeled reference to an annotated tag.                   
* <p>                                                                       
* If the ref cannot be peeled (as it does not refer to an annotated tag)    
* the peeled id stays null, but {@link org.eclipse.jgit.lib.Ref#isPeeled()} 
* will be true.                                                             
*                                                                           
* @param ref                                                                
*            The ref to peel                                                
* @return <code>ref</code> if …
```
> Issue #614: Resolve Deprecated API IDEA violations

- releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
> Issue #614: Resolve CallToSystemExit, string formatting and string builder IDEA violations

- releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
#614
Renamed `run(..)` -> `runPostGenerationAndPublication(..)`
> Issue #614: Resolve MethodWithTooManyParameters, Naming, Javadoc IDEA violations

- releasenotes-builder/pom.xml
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/MailingListPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/SourceforgeRssPublisher.java
- releasenotes-builder/src/main/java/com/github/checkstyle/publishers/TwitterPublisher.java
Java 11
['Files.readString()' or 'Files.writeString()' can be used (3)](https://teamcity.jetbrains.com/viewLog.html?buildId=3952165&tab=Inspection&buildTypeId=Checkstyle_ContributionIdeaInspectionsPullRequest#)
> infra: upgrade releasenotes builder to java 11

- releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
- releasenotes-builder/src/main/java/com/github/checkstyle/CliProcessor.java
- releasenotes-builder/src/main/java/com/github/checkstyle/Main.java
- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/main/java/com/github/checkstyle/globals/Result.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
Resolves bugs in  #670. Was not sure how to name this commit, so let me know what to rename it to.
Here is the output:
``` 
$ export READ_ONLY_TOKEN=xxx && export DRONE_PULL_REQUEST="master" && ./.ci/releasenotes-gen.sh
```
```
...
HEAD is now at 721550316 Issue #12319: validate PR number when commit is for PR
From https://github.com/checkstyle/checkstyle
* branch                master     -> FETCH_HEAD
Already up to date.
LATEST_RELEASE_TAG=checkstyle-10.3.4
CS_RELEASE_VERSION=10.3.5
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARN] Issue #12243 "Pitest/Checker: Drop New/Unnecessary Displays And Switch to Git Diff" is not …
```
> Pull #675: Fix releasenote-builder: should have execution mode to fail if release version (by pom) is not matching to issues labels

- devops/docker/README.md
- devops/docker/idea-image/Dockerfile
*Should* fix failure at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/15829/workflows/6457dceb-0274-4045-9593-b6ae93660de6/jobs/191927, there have been issues reported with newest cimg/openjdk
> infra: pin patch version of openjdk base image

- releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
> Issue #364: releasenotes-builder: avoid extra line wrapping

- releasenotes-builder/src/main/java/com/github/checkstyle/globals/ReleaseNotesMessage.java
- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/github_post.template
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
> Issue #652: releasenotes-builder: Release notes for GitHub shows escape at-symbol

- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/rssMlistMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
Resolves #701
---
For the manual test I modified the script to be pointing to this branch and changed `CS_RELEASE_VERSION` to `10.5.0`. Runs with no errors: https://github.com/stoyanK7/checkstyle/commit/dee3811dd6eb71765ccf3bc085763cfdf876042b
If I change `CS_RELEASE_VERSION` to `10.5.1`, it is failing as expected.
```
[WARN] Issue #11163 "Enforce file size on Java inputs" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11163
[WARN] Issue #11446 "Update Tests to use new 'verifyXxxxxx' method or 'execute' that use inlined config in Input files" is not closed! Please review issue https://github.com/checkstyle/checkstyle/issues/11446
[WARN] Issue #11214 "Specify violation messages in input files." is not closed! Please review issue …
```
> Issue #701: releasenotes builder: release version validation should work on digits

- releasenotes-builder/config/import-control.xml
- releasenotes-builder/config/suppressions.xml
- releasenotes-builder/pom.xml
- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/main/java/com/github/checkstyle/git/CsGit.java
- releasenotes-builder/src/main/java/com/github/checkstyle/git/package-info.java
- releasenotes-builder/src/main/java/com/github/checkstyle/github/CsGitHub.java
- releasenotes-builder/src/main/java/com/github/checkstyle/github/NotesBuilder.java
- releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
- releasenotes-builder/src/test/java/com/github/checkstyle/internal/GhIssueUtil.java
- releasenotes-builder/src/test/java/com/github/checkstyle/internal/RevCommitUtil.java
This is what brought the PR https://github.com/checkstyle/contribution/pull/703 . Alternate idea for https://github.com/checkstyle/contribution/issues/327#issuecomment-1326900135 .
This PR is not expected to pass CI yet, but it is a working example. This draft PR is looking for approval as being the future method for testing in this project.
Including @stoyanK7 .
This is rough example executing Main in a test with successful completion. No commits are returned, no errors produced. We can take this and make common test methods where we return specific commits, and can expand on other things like publishing failures (by throwing exceptions), and eventually test all aspects of our code.
Any API calls like Git, GitHub, Twitter, etc... are separated from the main logic and mocked to not really …
> Release notes mock test

- releasenotes-builder/src/main/resources/com/github/checkstyle/templates/xdoc_freemarker.template
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocAll.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
Resolves https://github.com/checkstyle/checkstyle/issues/12498
Github actions changes; https://github.com/stoyanK7/checkstyle/commit/4dba500002f3ee1c56b9d5552db18723b0802518
Actions job: https://github.com/stoyanK7/checkstyle/actions/runs/3614141814/jobs/6090376899
`<#t>` docs: https://freemarker.apache.org/docs/ref_directive_t.html#ref.directive.t
> Pull #721: Fix generated extra empty line with spaces in xdoc

- releasenotes-builder/pom.xml
- releasenotes-builder/src/main/java/com/github/checkstyle/CliOptions.java
- releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
- releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractPathTestSupport.java
- releasenotes-builder/src/test/java/com/github/checkstyle/internal/AbstractReleaseNotesTestSupport.java
- releasenotes-builder/src/test/java/com/github/checkstyle/internal/RevCommitUtil.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageAll.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocAll.txt
Discussed at https://github.com/checkstyle/contribution/pull/712#issuecomment-1336195814
Reworked and moved code around to build a new testing tier for release notes.
Commit `converts one test in TemplateProcess to the new layout` shows an example of converting an existing test to the new format.
Commit `ensure output location is treated as a directory` makes things easier if output location is always treated as a folder, otherwise we need to manually add `/` when passing it to Main as it doesn't save to the correct location.
> Rework test layout

- releasenotes-builder/src/main/java/com/github/checkstyle/MainProcess.java
- releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
Issue #727
it is not comprehended validation, but enough to avoid basic typos
> Issue #727: shallow validation of release number

- checkstyle-tester/README.md
- checkstyle-tester/diff.groovy
Issue #665
````
> groovy .\diff.groovy -r M:\checkstyle -p localtest -l M:\projects-to-test-on.properties
Error: you should specify either 'config', or 'baseConfig', or 'patchConfig'!
Caught: java.lang.IllegalArgumentException: Error: invalid command line arguments!
java.lang.IllegalArgumentException: Error: invalid command line arguments!
````
Program goes to completion with `-c my_check.xml`.
> Issue #665: adds validation of a configuration being required

- patch-diff-report-tool/src/main/resources/header.template
Issue #738
Confirmed deprecations are gone from test run.
Old:
````
Running com.github.checkstyle.MainTest
[main] WARN org.thymeleaf.standard.processor.StandardIncludeTagProcessor - [THYMELEAF][main][header] Deprecated attribute {th:include,data-th-include} found in template header, line 71, col 21. Please use {th:insert,data-th-insert} instead, this deprecated attribute will be removed in future versions of Thymeleaf.
[main] WARN org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor - [THYMELEAF][main][header] Deprecated unwrapped fragment expression "::module" found in template header, line 71, col 21. Please use the complete syntax of fragment expressions instead ("~{::module}"). The old, unwrapped syntax for fragment expressions will be removed in future …
```
> Issue #738: swaps deprecated attributes in patch-diff-report

- releasenotes-builder/pom.xml
There is no more tools with Java 11.
> minor: remove outdated properties from releasenotes-builder

- .github/workflows/bump_license_year.yml
Source: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
Proof of working: https://github.com/Vyom-Yadav/actions-test/commit/8ae3f4490e16f3bbba5f252f96b03e15198e8122
> infra: fix bump_license_year.yml not adding year to commit message

- .github/workflows/bump_license_year.yml
From https://github.com/checkstyle/checkstyle/issues/12572#issuecomment-1368578305
> Cron is slightly different to let naun repo be updated first, dependable repositores update after. Distance might be in 1-2 hour as in main repo queue is longer.
> infra: change cron in bump_license_year.yml

- releasenotes-builder/src/main/java/com/github/checkstyle/github/CommitMessage.java
- releasenotes-builder/src/test/java/com/github/checkstyle/MainTest.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
Part of https://github.com/checkstyle/checkstyle/issues/12717
> Additionally, we should fallback release notes categories to "misc" if something is wrong with parsing a format, we need to update release notes generator.
---
It seems we are already handling this case. The problem was that we were not checking for the hash `#` char in the commit message. We expect to see it as shown here
https://github.com/checkstyle/checkstyle/blob/a144e7fb576f6a875bf5a630190754ca025b7381/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L74-L75
> Pull #770: Boost implementation of isIssueOrPull method

- releasenotes-builder/src/main/java/com/github/checkstyle/github/CommitMessage.java
- releasenotes-builder/src/test/java/com/github/checkstyle/templates/TemplateProcessorTest.java
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/githubPageNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/twitterNew.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBreakingCompatibility.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocBug.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocMisc.txt
- releasenotes-builder/src/test/resources/com/github/checkstyle/xdocNew.txt
Resolves https://github.com/checkstyle/checkstyle/issues/12717#issuecomment-1426842225
> Hmm , and now we have a problem that release notes builder is not failing if labels are not defined.
>Should be red https://github.com/checkstyle/checkstyle/actions/runs/4149773299, as label on this issue is not defined for release notes.
>If issue is not closed, there use to be warning. But absence of label is error. I keep this issue open and without label to wait for fix.
`CommitMessageTest` trims them as well: 
https://github.com/checkstyle/checkstyle/blob/a144e7fb576f6a875bf5a630190754ca025b7381/src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java#L190-L194
---
```sh
 stoyan @  zenbook:  ~/open-source/checkstyle …
```
> Pull #771: Trim newlines in isIssueOrPull method

- checkstyle-tester/README.md
- checkstyle-tester/diff.groovy
This reverts commit f10f82a9c036fc4565b4868d7cc8b0a3fe6eea2d.
We damaged ability to check out a specific SHA/ branch somehow. 
From failing [build](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23498/workflows/f5bbd3dc-3865-40f5-a44a-6bb41a9541df/jobs/501286/parallel-runs/0/steps/0-103?invite=true#step-103-33601_26): 
```
Testing Checkstyle started
[delete] Deleting directory /home/circleci/project/.ci-temp/contribution/checkstyle-tester/src/main/java
Cloning git repository 'pmd' to repositories/pmd folder ...
Cloning command: git clone https://github.com/pmd/pmd repositories/pmd
Cloning into 'repositories/pmd'...
Cloning git repository 'pmd' - completed
pmd is synchronized
[copy] Copying 4891 files to /home/circleci/project/.ci-temp/contribution/checkstyle-tester/src/mai …
```
> Revert "Issue #818: do shallow clone to speedup download"

- checkstyle-tester/codenarc.sh
- checkstyle-tester/diff.groovy
Aims to close Issue https://github.com/checkstyle/contribution/issues/757
The version of codenarc being used was outdated through `v1.5`
As part of the commit, I have bumped `codenarc version` to highest compatible `v2.2.0`
var_names in file [diff.groovy](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy) were found violating VariableName rule. These have been modified to adhere to checkstyle rules.
Prior changes : 
```
final REPO_NAME_PARAM_NO = 0
final REPO_TYPE_PARAM_NO = 1
final REPO_URL_PARAM_NO = 2
final REPO_COMMIT_ID_PARAM_NO = 3
final REPO_EXCLUDES_PARAM_NO = 4
final FULL_PARAM_LIST_SIZE = 5
```
After changes : 
```
final repoNameParamNo = 0
final repoTypeParamNo = 1
final repoURLParamNo = 2
final repoCommitIDParamNo = 3
final …
```
> Issue #757: Bumped Codenarc to version v2.2.0

- devops/docker/idea-image/Dockerfile
Aims to close https://github.com/checkstyle/checkstyle/issues/14448
Link to PR in Checkstyle main repo with updated docker image : https://github.com/checkstyle/checkstyle/pull/14604
IDEA version used : v`2023.3.4`  (latest release)
```
Version: 2023.3.4
Build: 233.14475.28
13 February 2024
```
https://www.jetbrains.com/idea/download/?section=linux
Link to docker image used for testing update : 
https://hub.docker.com/repository/docker/manishkk07/manish-k-07-checkstyle/tags?page=1&ordering=last_updated
To pull image : `docker pull manishkk07/manish-k-07-checkstyle:jdk11-idea2023.3.4`
> Issue #14448: Updated IDEA version to v2023.3.4

- devops/docker/idea-image/Dockerfile
Aims to close https://github.com/checkstyle/checkstyle/issues/14448
Follow-up of https://github.com/checkstyle/checkstyle/pull/14604 and #837 
Based on observations from https://github.com/checkstyle/checkstyle/pull/14604#discussion_r1530584190 and further discussions.
last time we upgraded `2022.2.2` -> `2023.3.4`  at
https://github.com/checkstyle/contribution/commit/80a61391a97ac64f48d1ebef333c2910cd85b795 , but latest is problematic with scopes.
The latest IDEA release that we have used for update (2023.3.4) had issues with scopes.
A bit of research on different versions landed me on `v2022.3.3` being stable and good with scopes.
Link to PR in Checkstyle main repo with updated docker image : https://github.com/checkstyle/checkstyle/pull/14696
Link to docker image (personal) for testing …
> Issue #14448: Migrate IDEA to highest true-scopes release v2022.3.3

- .ci/validation.sh
- appveyor.yml
- checkstyle-tester/README.md
- checkstyle-tester/diff.groovy
Resolves #818 
This PR reuses the earlier PR on shallow clone PR, while  reverted retaining checkout abilitiy to specific SHA. 
I tested this PR on main repo https://github.com/checkstyle/checkstyle/pull/14662, by following the footprints of what already has been done. I am attaching the test results below:
**Successful build while retaining checkout to specific SHA:**
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/25238/workflows/51a420a4-ff1f-4137-89c0-802b6ecfcd81/jobs/577549
```
Testing Checkstyle started
[delete] Deleting directory /home/circleci/project/.ci-temp/contribution/checkstyle-tester/src/main/java
Cloning git repository 'pmd' to repositories/pmd folder ...
Cloning into 'repositories/pmd'...
Cloning git repository 'pmd' - completed
Running command: git fetch …
```
> Issue #818: do shallow clone while retaining checkout abilitiy to specific SHA

- checkstyle-tester/checks-only-javadoc-error.xml
added `JavadocLeadingAsteriskAlign` check to `checkstyle-tester/checks-only-javadoc-error.xml`
> add new check: JavadocLeadingAsteriskAlign

- checkstyle-tester/my_check.xml
blocked until https://github.com/checkstyle/checkstyle/pull/15204
> Config: use new treewalker property to skip non-compiled files in regression

- .circleci/config.yml
Issue: #944
PR updates the markdown lint job to use the official cimg/ruby:3.2 Docker image, which includes Ruby 3.2+. This satisfies the version requirement of mdl and allows the job to complete successfully.
> Issue #944: Using compatible ruby version
